/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTID_LIST_H_
#define GROASTID_LIST_H_

#include <caterpillar.h>
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_ID_LIST              (groast_id_list_get_type())
#define GROAST_ID_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_id_list_get_type(), GroAstIdList))
#define GROAST_ID_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_ID_LIST, GroAstIdListClass))
#define GROAST_IS_ID_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_ID_LIST))
#define GROAST_IS_ID_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_ID_LIST))
#define GROAST_ID_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_ID_LIST, GroAstIdListClass))


typedef struct _GroAstIdList               GroAstIdList;
typedef struct _GroAstIdListPrivate        GroAstIdListPrivate;
typedef struct _GroAstIdListClass          GroAstIdListClass;


struct _GroAstIdList {
	GObject parent;
};

struct _GroAstIdListClass {
	GObjectClass parent_class;
};


GType groast_id_list_get_type();

CatArrayWo *groast_id_list_enlist(GroAstIdList *self);
GroAstIdList *groast_id_list_new_1(GroRunIToken *ids, GroRunIToken *id);
GroAstIdList *groast_id_list_new_2(GroRunIToken *id);
GroRunIToken *groast_id_list_tk_ids(GroAstIdList *self);
GroAstIdList *groast_id_list_get_ids(GroAstIdList *self);
GroRunIToken *groast_id_list_tk_id(GroAstIdList *self);
CatStringWo *groast_id_list_get_id(GroAstIdList *self);

G_END_DECLS

#endif /* GROASTID_LIST_H_ */
