/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastterminaldeclaration.h"

struct _GroAstTerminalDeclarationPrivate {
	GroRunIToken *ids;
};


G_DEFINE_TYPE_WITH_CODE(GroAstTerminalDeclaration, groast_terminal_declaration, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstTerminalDeclaration)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_terminal_declaration_class_init(GroAstTerminalDeclarationClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_terminal_declaration_init(GroAstTerminalDeclaration *instance) {
}

static void l_dispose(GObject *object) {
	GroAstTerminalDeclaration *instance = GROAST_TERMINAL_DECLARATION(object);
	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ids);
	G_OBJECT_CLASS(groast_terminal_declaration_parent_class)->dispose(object);
}

CatArrayWo *groast_terminal_declaration_enlist(GroAstTerminalDeclaration *self) {

	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(self);
	if (priv->ids==NULL) {
		return NULL;
	}
	return groast_id_list_enlist((GroAstIdList *) grorun_itoken_get_value(priv->ids));
  
}

GroAstTerminalDeclaration *groast_terminal_declaration_new_1(GroRunIToken *ids) {
	GroAstTerminalDeclaration *instance = g_object_new(GROAST_TYPE_TERMINAL_DECLARATION, NULL);
	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(instance);
	priv->ids = L_SAFE_REF_PTR(ids);
	return instance;
}

GroAstTerminalDeclaration *groast_terminal_declaration_new_2() {
	GroAstTerminalDeclaration *instance = g_object_new(GROAST_TYPE_TERMINAL_DECLARATION, NULL);
	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(instance);
	priv->ids = NULL;
	return instance;
}

GroRunIToken *groast_terminal_declaration_tk_ids(GroAstTerminalDeclaration *self) {
	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(self);
	return priv->ids;
}

GroAstIdList *groast_terminal_declaration_get_ids(GroAstTerminalDeclaration *self) {
	GroAstTerminalDeclarationPrivate *priv = groast_terminal_declaration_get_instance_private(self);
	return (GroAstIdList *) grorun_itoken_get_value(priv->ids);
}

