/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastrhssublist.h"
#include "../../src/ast/groastirhsenlistable.h"

struct _GroAstRhsSubListPrivate {
	GroRunIToken *sub;
	GroRunIToken *subList;
};

static void l_irhs_enlistable_iface_init(GroAstIRhsEnlistableInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GroAstRhsSubList, groast_rhs_sub_list, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstRhsSubList)
		G_IMPLEMENT_INTERFACE(GROAST_TYPE_IRHS_ENLISTABLE, l_irhs_enlistable_iface_init)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_rhs_sub_list_class_init(GroAstRhsSubListClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_rhs_sub_list_init(GroAstRhsSubList *instance) {
}

static void l_dispose(GObject *object) {
	GroAstRhsSubList *instance = GROAST_RHS_SUB_LIST(object);
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->sub);
	L_SAFE_UNREF_PTR(priv->subList);
	G_OBJECT_CLASS(groast_rhs_sub_list_parent_class)->dispose(object);
}

CatArrayWo *groast_rhs_sub_list_enlist(GroAstRhsSubList *self) {
 
	CatArrayWo *result = cat_array_wo_new();
	GroAstRhsSubList *tdl = self;
	while(tdl) {
		GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(tdl);
		cat_array_wo_append(result, (GObject *) priv->sub);
		if (priv->subList==NULL) {
			break;
		}
		tdl = (GroAstRhsSubList *) grorun_itoken_get_value(priv->subList);
	}
	cat_array_wo_reverse(result);
	return result;
  
}

GroAstRhsSubList *groast_rhs_sub_list_new_1(GroRunIToken *subList, GroRunIToken *sub) {
	GroAstRhsSubList *instance = g_object_new(GROAST_TYPE_RHS_SUB_LIST, NULL);
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(instance);
	priv->sub = L_SAFE_REF_PTR(sub);
	priv->subList = L_SAFE_REF_PTR(subList);
	return instance;
}

GroAstRhsSubList *groast_rhs_sub_list_new_2(GroRunIToken *sub) {
	GroAstRhsSubList *instance = g_object_new(GROAST_TYPE_RHS_SUB_LIST, NULL);
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(instance);
	priv->sub = L_SAFE_REF_PTR(sub);
	priv->subList = NULL;
	return instance;
}

GroRunIToken *groast_rhs_sub_list_tk_sub(GroAstRhsSubList *self) {
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(self);
	return priv->sub;
}

GroAstIRhsPart *groast_rhs_sub_list_get_sub(GroAstRhsSubList *self) {
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(self);
	return (GroAstIRhsPart *) grorun_itoken_get_value(priv->sub);
}

GroRunIToken *groast_rhs_sub_list_tk_subList(GroAstRhsSubList *self) {
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(self);
	return priv->subList;
}

GroAstIRhsPart *groast_rhs_sub_list_get_subList(GroAstRhsSubList *self) {
	GroAstRhsSubListPrivate *priv = groast_rhs_sub_list_get_instance_private(self);
	return (GroAstIRhsPart *) grorun_itoken_get_value(priv->subList);
}


/******************** start GroAstIRhsEnlistable implementation  ********************/


static void l_irhs_enlistable_iface_init(GroAstIRhsEnlistableInterface *iface) {

  	iface->enlist = (GroAstEnlistFunc) groast_rhs_sub_list_enlist;
  
}

/******************** end GroAstIRhsEnlistable implementation ********************/

