/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTRHS_RULE_PART_LIST_H_
#define GROASTRHS_RULE_PART_LIST_H_

#include "grorunfork.h"
#include "../../src/ast/groastirhspart.h"

G_BEGIN_DECLS

#define GROAST_TYPE_RHS_RULE_PART_LIST              (groast_rhs_rule_part_list_get_type())
#define GROAST_RHS_RULE_PART_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_rhs_rule_part_list_get_type(), GroAstRhsRulePartList))
#define GROAST_RHS_RULE_PART_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_RHS_RULE_PART_LIST, GroAstRhsRulePartListClass))
#define GROAST_IS_RHS_RULE_PART_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_RHS_RULE_PART_LIST))
#define GROAST_IS_RHS_RULE_PART_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_RHS_RULE_PART_LIST))
#define GROAST_RHS_RULE_PART_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_RHS_RULE_PART_LIST, GroAstRhsRulePartListClass))


typedef struct _GroAstRhsRulePartList               GroAstRhsRulePartList;
typedef struct _GroAstRhsRulePartListPrivate        GroAstRhsRulePartListPrivate;
typedef struct _GroAstRhsRulePartListClass          GroAstRhsRulePartListClass;


struct _GroAstRhsRulePartList {
	GObject parent;
};

struct _GroAstRhsRulePartListClass {
	GObjectClass parent_class;
};


GType groast_rhs_rule_part_list_get_type();

CatArrayWo *groast_rhs_rule_part_list_enlist(GroAstRhsRulePartList *self);
GroAstRhsRulePartList *groast_rhs_rule_part_list_new_1(GroRunIToken *rulePartList, GroRunIToken *rulePart);
GroRunIToken *groast_rhs_rule_part_list_tk_rulePart(GroAstRhsRulePartList *self);
GroAstIRhsPart *groast_rhs_rule_part_list_get_rulePart(GroAstRhsRulePartList *self);
GroRunIToken *groast_rhs_rule_part_list_tk_rulePartList(GroAstRhsRulePartList *self);
GroAstRhsRulePartList *groast_rhs_rule_part_list_get_rulePartList(GroAstRhsRulePartList *self);

G_END_DECLS

#endif /* GROASTRHS_RULE_PART_LIST_H_ */
