/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastsymbolpart.h"

struct _GroAstSymbolPartPrivate {
	GroRunIToken *symName;
	GroRunIToken *label;
};


G_DEFINE_TYPE_WITH_CODE(GroAstSymbolPart, groast_symbol_part, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstSymbolPart)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_symbol_part_class_init(GroAstSymbolPartClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_symbol_part_init(GroAstSymbolPart *instance) {
}

static void l_dispose(GObject *object) {
	GroAstSymbolPart *instance = GROAST_SYMBOL_PART(object);
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->symName);
	L_SAFE_UNREF_PTR(priv->label);
	G_OBJECT_CLASS(groast_symbol_part_parent_class)->dispose(object);
}

GroAstSymbolPart *groast_symbol_part_new_1(GroRunIToken *symName, GroRunIToken *label) {
	GroAstSymbolPart *instance = g_object_new(GROAST_TYPE_SYMBOL_PART, NULL);
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(instance);
	priv->symName = L_SAFE_REF_PTR(symName);
	priv->label = L_SAFE_REF_PTR(label);
	return instance;
}

GroRunIToken *groast_symbol_part_tk_symName(GroAstSymbolPart *self) {
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(self);
	return priv->symName;
}

CatStringWo *groast_symbol_part_get_symName(GroAstSymbolPart *self) {
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->symName);
}

GroRunIToken *groast_symbol_part_tk_label(GroAstSymbolPart *self) {
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(self);
	return priv->label;
}

CatStringWo *groast_symbol_part_get_label(GroAstSymbolPart *self) {
	GroAstSymbolPartPrivate *priv = groast_symbol_part_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->label);
}

