/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTPROD_RULE_REF_H_
#define GROASTPROD_RULE_REF_H_

#include <caterpillar.h>
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_PROD_RULE_REF              (groast_prod_rule_ref_get_type())
#define GROAST_PROD_RULE_REF(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_prod_rule_ref_get_type(), GroAstProdRuleRef))
#define GROAST_PROD_RULE_REF_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_PROD_RULE_REF, GroAstProdRuleRefClass))
#define GROAST_IS_PROD_RULE_REF(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_PROD_RULE_REF))
#define GROAST_IS_PROD_RULE_REF_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_PROD_RULE_REF))
#define GROAST_PROD_RULE_REF_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_PROD_RULE_REF, GroAstProdRuleRefClass))


typedef struct _GroAstProdRuleRef               GroAstProdRuleRef;
typedef struct _GroAstProdRuleRefPrivate        GroAstProdRuleRefPrivate;
typedef struct _GroAstProdRuleRefClass          GroAstProdRuleRefClass;


struct _GroAstProdRuleRef {
	GObject parent;
};

struct _GroAstProdRuleRefClass {
	GObjectClass parent_class;
};


GType groast_prod_rule_ref_get_type();

GroAstProdRuleRef *groast_prod_rule_ref_new_1(GroRunIToken *lhsName);
GroAstProdRuleRef *groast_prod_rule_ref_new_2(GroRunIToken *lhsName, GroRunIToken *label);
GroAstProdRuleRef *groast_prod_rule_ref_new_3(GroRunIToken *lhsName, GroRunIToken *offset);
GroRunIToken *groast_prod_rule_ref_tk_lhsName(GroAstProdRuleRef *self);
CatStringWo *groast_prod_rule_ref_get_lhsName(GroAstProdRuleRef *self);
GroRunIToken *groast_prod_rule_ref_tk_offset(GroAstProdRuleRef *self);
CatInteger *groast_prod_rule_ref_get_offset(GroAstProdRuleRef *self);
GroRunIToken *groast_prod_rule_ref_tk_label(GroAstProdRuleRef *self);
CatStringWo *groast_prod_rule_ref_get_label(GroAstProdRuleRef *self);

G_END_DECLS

#endif /* GROASTPROD_RULE_REF_H_ */
