/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastidlist.h"

struct _GroAstIdListPrivate {
	GroRunIToken *ids;
	GroRunIToken *id;
};


G_DEFINE_TYPE_WITH_CODE(GroAstIdList, groast_id_list, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstIdList)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_id_list_class_init(GroAstIdListClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_id_list_init(GroAstIdList *instance) {
}

static void l_dispose(GObject *object) {
	GroAstIdList *instance = GROAST_ID_LIST(object);
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ids);
	L_SAFE_UNREF_PTR(priv->id);
	G_OBJECT_CLASS(groast_id_list_parent_class)->dispose(object);
}

CatArrayWo *groast_id_list_enlist(GroAstIdList *self) {
 
	CatArrayWo *result = cat_array_wo_new();
	GroAstIdList *tdl = self;
	while(tdl) {
		GroAstIdListPrivate *priv = groast_id_list_get_instance_private(tdl);
		cat_array_wo_append(result, (GObject *) priv->id);
		if (priv->ids==NULL) {
			break;
		}
		tdl = (GroAstIdList *) grorun_itoken_get_value(priv->ids);
	}
	cat_array_wo_reverse(result);
	return result;
  
}

GroAstIdList *groast_id_list_new_1(GroRunIToken *ids, GroRunIToken *id) {
	GroAstIdList *instance = g_object_new(GROAST_TYPE_ID_LIST, NULL);
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(instance);
	priv->ids = L_SAFE_REF_PTR(ids);
	priv->id = L_SAFE_REF_PTR(id);
	return instance;
}

GroAstIdList *groast_id_list_new_2(GroRunIToken *id) {
	GroAstIdList *instance = g_object_new(GROAST_TYPE_ID_LIST, NULL);
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(instance);
	priv->ids = NULL;
	priv->id = L_SAFE_REF_PTR(id);
	return instance;
}

GroRunIToken *groast_id_list_tk_ids(GroAstIdList *self) {
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(self);
	return priv->ids;
}

GroAstIdList *groast_id_list_get_ids(GroAstIdList *self) {
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(self);
	return (GroAstIdList *) grorun_itoken_get_value(priv->ids);
}

GroRunIToken *groast_id_list_tk_id(GroAstIdList *self) {
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(self);
	return priv->id;
}

CatStringWo *groast_id_list_get_id(GroAstIdList *self) {
	GroAstIdListPrivate *priv = groast_id_list_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->id);
}

