/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTTYPE_DEFINITION_LIST_H_
#define GROASTTYPE_DEFINITION_LIST_H_

#include "grorunfork.h"
#include "groasttypedefinition.h"

G_BEGIN_DECLS

#define GROAST_TYPE_TYPE_DEFINITION_LIST              (groast_type_definition_list_get_type())
#define GROAST_TYPE_DEFINITION_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_type_definition_list_get_type(), GroAstTypeDefinitionList))
#define GROAST_TYPE_DEFINITION_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_TYPE_DEFINITION_LIST, GroAstTypeDefinitionListClass))
#define GROAST_IS_TYPE_DEFINITION_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_TYPE_DEFINITION_LIST))
#define GROAST_IS_TYPE_DEFINITION_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_TYPE_DEFINITION_LIST))
#define GROAST_TYPE_DEFINITION_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_TYPE_DEFINITION_LIST, GroAstTypeDefinitionListClass))


typedef struct _GroAstTypeDefinitionList               GroAstTypeDefinitionList;
typedef struct _GroAstTypeDefinitionListPrivate        GroAstTypeDefinitionListPrivate;
typedef struct _GroAstTypeDefinitionListClass          GroAstTypeDefinitionListClass;


struct _GroAstTypeDefinitionList {
	GObject parent;
};

struct _GroAstTypeDefinitionListClass {
	GObjectClass parent_class;
};


GType groast_type_definition_list_get_type();

CatArrayWo *groast_type_definition_list_enlist(GroAstTypeDefinitionList *self);
GroAstTypeDefinitionList *groast_type_definition_list_new_1(GroRunIToken *tdList, GroRunIToken *typeDef);
GroRunIToken *groast_type_definition_list_tk_tdList(GroAstTypeDefinitionList *self);
GroAstTypeDefinitionList *groast_type_definition_list_get_tdList(GroAstTypeDefinitionList *self);
GroRunIToken *groast_type_definition_list_tk_typeDef(GroAstTypeDefinitionList *self);
GroAstTypeDefinition *groast_type_definition_list_get_typeDef(GroAstTypeDefinitionList *self);

G_END_DECLS

#endif /* GROASTTYPE_DEFINITION_LIST_H_ */
