/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTCODE_DEFINITION_LIST_H_
#define GROASTCODE_DEFINITION_LIST_H_

#include "groastcodedefinition.h"
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_CODE_DEFINITION_LIST              (groast_code_definition_list_get_type())
#define GROAST_CODE_DEFINITION_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_code_definition_list_get_type(), GroAstCodeDefinitionList))
#define GROAST_CODE_DEFINITION_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_CODE_DEFINITION_LIST, GroAstCodeDefinitionListClass))
#define GROAST_IS_CODE_DEFINITION_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_CODE_DEFINITION_LIST))
#define GROAST_IS_CODE_DEFINITION_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_CODE_DEFINITION_LIST))
#define GROAST_CODE_DEFINITION_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_CODE_DEFINITION_LIST, GroAstCodeDefinitionListClass))


typedef struct _GroAstCodeDefinitionList               GroAstCodeDefinitionList;
typedef struct _GroAstCodeDefinitionListPrivate        GroAstCodeDefinitionListPrivate;
typedef struct _GroAstCodeDefinitionListClass          GroAstCodeDefinitionListClass;


struct _GroAstCodeDefinitionList {
	GObject parent;
};

struct _GroAstCodeDefinitionListClass {
	GObjectClass parent_class;
};


GType groast_code_definition_list_get_type();

GroAstCodeDefinitionList *groast_code_definition_list_new_1(GroRunIToken *cdList, GroRunIToken *codeDef);
GroRunIToken *groast_code_definition_list_tk_cdList(GroAstCodeDefinitionList *self);
GroAstCodeDefinitionList *groast_code_definition_list_get_cdList(GroAstCodeDefinitionList *self);
GroRunIToken *groast_code_definition_list_tk_codeDef(GroAstCodeDefinitionList *self);
GroAstCodeDefinition *groast_code_definition_list_get_codeDef(GroAstCodeDefinitionList *self);

G_END_DECLS

#endif /* GROASTCODE_DEFINITION_LIST_H_ */
