/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTSPEC_H_
#define GROASTSPEC_H_

#include "groastterminaldeclarationlist.h"
#include "groastproductiondefinitionlist.h"
#include <caterpillar.h>
#include "groasttypedefinitionlist.h"
#include "grorunfork.h"
#include "groastcodedefinitionlist.h"

G_BEGIN_DECLS

#define GROAST_TYPE_SPEC              (groast_spec_get_type())
#define GROAST_SPEC(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_spec_get_type(), GroAstSpec))
#define GROAST_SPEC_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_SPEC, GroAstSpecClass))
#define GROAST_IS_SPEC(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_SPEC))
#define GROAST_IS_SPEC_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_SPEC))
#define GROAST_SPEC_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_SPEC, GroAstSpecClass))


typedef struct _GroAstSpec               GroAstSpec;
typedef struct _GroAstSpecPrivate        GroAstSpecPrivate;
typedef struct _GroAstSpecClass          GroAstSpecClass;


struct _GroAstSpec {
	GObject parent;
};

struct _GroAstSpecClass {
	GObjectClass parent_class;
};


GType groast_spec_get_type();

GroAstSpec *groast_spec_new_1(GroRunIToken *td, GroRunIToken *pl, GroRunIToken *im, GroRunIToken *tl, GroRunIToken *cl);
GroAstSpec *groast_spec_new_2(GroRunIToken *td, GroRunIToken *pl);
GroRunIToken *groast_spec_tk_td(GroAstSpec *self);
GroAstTerminalDeclarationList *groast_spec_get_td(GroAstSpec *self);
GroRunIToken *groast_spec_tk_im(GroAstSpec *self);
CatStringWo *groast_spec_get_im(GroAstSpec *self);
GroRunIToken *groast_spec_tk_tl(GroAstSpec *self);
GroAstTypeDefinitionList *groast_spec_get_tl(GroAstSpec *self);
GroRunIToken *groast_spec_tk_cl(GroAstSpec *self);
GroAstCodeDefinitionList *groast_spec_get_cl(GroAstSpec *self);
GroRunIToken *groast_spec_tk_pl(GroAstSpec *self);
GroAstProductionDefinitionList *groast_spec_get_pl(GroAstSpec *self);

G_END_DECLS

#endif /* GROASTSPEC_H_ */
