/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GROASTLINE_BODY_H_
#define GROASTLINE_BODY_H_

#include <grossruntime.h>
#include "groasttypedescription.h"

G_BEGIN_DECLS

#define GROAST_TYPE_LINE_BODY              (groast_line_body_get_type())
#define GROAST_LINE_BODY(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_line_body_get_type(), GroAstLineBody))
#define GROAST_LINE_BODY_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_LINE_BODY, GroAstLineBodyClass))
#define GROAST_IS_LINE_BODY(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_LINE_BODY))
#define GROAST_IS_LINE_BODY_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_LINE_BODY))
#define GROAST_LINE_BODY_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_LINE_BODY, GroAstLineBodyClass))


typedef struct _GroAstLineBody               GroAstLineBody;
typedef struct _GroAstLineBodyPrivate        GroAstLineBodyPrivate;
typedef struct _GroAstLineBodyClass          GroAstLineBodyClass;


struct _GroAstLineBody {
	GObject parent;
};

struct _GroAstLineBodyClass {
	GObjectClass parent_class;
};


GType groast_line_body_get_type();

GroAstLineBody *groast_line_body_new_1(GroRunIToken *statement);
GroRunIToken *groast_line_body_tk_statement(GroAstLineBody *self);
GroAstTypeDescription *groast_line_body_get_statement(GroAstLineBody *self);

G_END_DECLS

#endif /* GROASTLINE_BODY_H_ */
