/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "groastlines.h"

struct _GroAstLinesPrivate {
	GroRunIToken *ast_lines;
	GroRunIToken *ast_line;
};


G_DEFINE_TYPE_WITH_CODE(GroAstLines, groast_lines, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstLines)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void groast_lines_class_init(GroAstLinesClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_lines_init(GroAstLines *instance) {
}

static void l_dispose(GObject *object) {
	GroAstLines *instance = groast_lines(object);
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ast_lines);
	L_SAFE_UNREF_PTR(priv->ast_line);
	G_OBJECT_CLASS(groast_lines_parent_class)->dispose(object);
}

GroAstLines *groast_lines_new_1(GroRunIToken *ast_lines, GroRunIToken *ast_line) {
	GroAstLines *instance = g_object_new(GROAST_TYPE_LINES, NULL);
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(instance);
	priv->ast_lines = g_object_ref(ast_lines);
	priv->ast_line = g_object_ref(ast_line);
	return instance;
}

GroAstLines *groast_lines_new_2(GroRunIToken *ast_line) {
	GroAstLines *instance = g_object_new(GROAST_TYPE_LINES, NULL);
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(instance);
	priv->ast_lines = NULL;
	priv->ast_line = g_object_ref(ast_line);
	return instance;
}

GroRunIToken *groast_lines_tk_ast_lines(GroAstLines *self) {
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(self);
	return priv->ast_lines;
}

GroAstLines *groast_lines_get_ast_lines(GroAstLines *self) {
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(self);
	return (GroAstLines *) grorun_itoken_get_value(priv->ast_lines);
}

GroRunIToken *groast_lines_tk_ast_line(GroAstLines *self) {
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(self);
	return priv->ast_line;
}

GroAstLine *groast_lines_get_ast_line(GroAstLines *self) {
	GroAstLinesPrivate *priv = groast_lines_get_instance_private(self);
	return (GroAstLine *) grorun_itoken_get_value(priv->ast_line);
}

