/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "grtastastactions.h"

static void l_iaction_handler_iface_init(GroRunIActionHandlerInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GrtAstAstActions, grtast_ast_actions, G_TYPE_OBJECT,
		G_IMPLEMENT_INTERFACE(GRORUN_TYPE_IACTION_HANDLER, l_iaction_handler_iface_init)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void grtast_ast_actions_class_init(GrtAstAstActionsClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void grtast_ast_actions_init(GrtAstAstActions *instance) {
}

static void l_dispose(GObject *object) {
	GrtAstAstActions *instance = grtast_ast_actions(object);
	G_OBJECT_CLASS(grtast_ast_actions_parent_class)->dispose(object);
}


/******************** start GroRunIActionHandler implementation  ********************/

static GroRunIToken *l_extract(GroRunFork *fork, GroRunReduceLayout *reduce_layout, int offset) {
	GroRunIToken *result = NULL;
	int rloff = grorun_reduce_layout_calculate_stack_offset(reduce_layout, offset);
	GroRunStackEntry *fe = grorun_fork_get_entry(fork, rloff);
	if (fe!=NULL) {
		result = grorun_stack_entry_get_lookahead(fe);
	}
	return result;
}


GObject *l_iaction_handler_run_action(GroRunIActionHandler *self, GroRunFork *fork, GroRunReduceLayout *reduce_layout, int action_id) {
	GObject result = NULL;
	int prod_id = grorun_reduce_layout_get_production_id(reduce_layout);
	switch(prod_id) {

		case 2 : {
			GroRunIToken *ast_lines = l_extract(fork, reduce_layout, 0);
			GroRunIToken *ast_line = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_lines_new_1(ast_lines, ast_line);
		} break;

		case 8 : {
			GroRunIToken *extendsTypeName = l_extract(fork, reduce_layout, 1);
			result = grorun_itoken_get_value(extendsTypeName);
		} break;

		case 4 : {
			GroRunIToken *name = l_extract(fork, reduce_layout, 0);
			GroRunIToken *line_body = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_line_new_1(name, line_body);
		} break;

		case 5 : {
			GroRunIToken *name = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_line_new_2(name);
		} break;

		case 3 : {
			GroRunIToken *ast_line = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_lines_new_2(ast_line);
		} break;

		case 1 : {
			GroRunIToken *ast_lines = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_file_new_1(ast_lines);
		} break;

		case 7 : {
			GroRunIToken *description = l_extract(fork, reduce_layout, 1);
			GroRunIToken *opt_extends = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_type_description_new_1(description, opt_extends);
		} break;

		case 6 : {
			GroRunIToken *statement = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_line_body_new_1(statement);
		} break;
	}
	return result;

}


static void l_iaction_handler_iface_init(GroRunIActionHandlerInterface *iface) {
	iface->runAction = l_iaction_handler_run_action;
}

/******************** end GroRunIActionHandler implementation ********************/

