/* This file was generated by Gross-CC on 2016.11.25 AD at 13:38:25 CET */
#include "groactions.h"
#include <grossruntime.h>



#include <logging/catlogdefs.h>
#define CAT_LOG_LEVEL CAT_LOG_WARN
#define CAT_LOG_CLAZZ "GroActions"
#include <logging/catlog.h>

static void l_action_handler_iface_init(GroRunIActionHandlerInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GroActions, gro_actions, G_TYPE_OBJECT,
		G_IMPLEMENT_INTERFACE(GRORUN_TYPE_IACTION_HANDLER, l_action_handler_iface_init)
);

static void l_finalize(GObject *object);
static void gro_actions_class_init(GroActionsClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->finalize = l_finalize;
}
static void gro_actions_init(GroActions *instance) {
}
static void l_finalize(GObject *object) {
	cat_log_detail("finalize:%p", object);
	cat_ref_denounce(object);
	G_OBJECT_CLASS(gro_actions_parent_class)->finalize(object);
	cat_log_detail("finalized:%p", object);
}
GroActions *gro_actions_new() {
	GroActions *result = g_object_new(GRO_TYPE_ACTIONS, NULL);
	cat_ref_anounce(result);
	return result;
}

static GroRunStackEntry *l_extract(GroRunFork *fork, GroRunReduceLayout *reduce_layout, int offset) {
	int rloff = grorun_reduce_layout_calculate_stack_offset(reduce_layout, offset);
	return  grorun_fork_get_entry(fork, rloff);
}


static GObject *l_run_action(GroRunIActionHandler *self, GroRunFork *fork, GroRunReduceLayout *reduce_layout, int action_id) {
	void *result = NULL;
	switch(action_id) {
	}
	return (GObject *) result;
}

static void l_action_handler_iface_init(GroRunIActionHandlerInterface *iface) {
	iface->runAction = l_run_action;
}
