#ifndef SPISYMBOL_H
#define SPISYMBOL_H

/* terminals */
#define SPI_SYMBOL_TERM_EOF                       0
#define SPI_SYMBOL_TERM_ERROR                     1
#define SPI_SYMBOL_TERM_FUNCTION                  2
#define SPI_SYMBOL_TERM_VAR                       3
#define SPI_SYMBOL_TERM_RETURN                    4
#define SPI_SYMBOL_TERM_IF                        5
#define SPI_SYMBOL_TERM_ELSE                      6
#define SPI_SYMBOL_TERM_THIS                      7
#define SPI_SYMBOL_TERM_FOR                       8
#define SPI_SYMBOL_TERM_ID                        9
#define SPI_SYMBOL_TERM_NULL                      10
#define SPI_SYMBOL_TERM_TRUE                      11
#define SPI_SYMBOL_TERM_FALSE                     12
#define SPI_SYMBOL_TERM_NUMBER                    13
#define SPI_SYMBOL_TERM_STRING                    14
#define SPI_SYMBOL_TERM_LPAREN                    15
#define SPI_SYMBOL_TERM_RPAREN                    16
#define SPI_SYMBOL_TERM_LBRACE                    17
#define SPI_SYMBOL_TERM_RBRACE                    18
#define SPI_SYMBOL_TERM_SEMI                      19
#define SPI_SYMBOL_TERM_COMMA                     20
#define SPI_SYMBOL_TERM_ASS_IS                    21
#define SPI_SYMBOL_TERM_QUESTION                  22
#define SPI_SYMBOL_TERM_COLON                     23
#define SPI_SYMBOL_TERM_OP_LOR                    24
#define SPI_SYMBOL_TERM_OP_LAND                   25
#define SPI_SYMBOL_TERM_OP_BOR                    26
#define SPI_SYMBOL_TERM_OP_BXOR                   27
#define SPI_SYMBOL_TERM_OP_BAND                   28
#define SPI_SYMBOL_TERM_DELETE                    29
#define SPI_SYMBOL_TERM_VOID                      30
#define SPI_SYMBOL_TERM_TYPEOF                    31
#define SPI_SYMBOL_TERM_OP_INC                    32
#define SPI_SYMBOL_TERM_OP_DEC                    33
#define SPI_SYMBOL_TERM_OP_ADD                    34
#define SPI_SYMBOL_TERM_OP_SUB                    35
#define SPI_SYMBOL_TERM_OP_NEG                    36
#define SPI_SYMBOL_TERM_OP_NOT                    37
#define SPI_SYMBOL_TERM_OP_MUL                    38
#define SPI_SYMBOL_TERM_OP_DIV                    39
#define SPI_SYMBOL_TERM_OP_MOD                    40
#define SPI_SYMBOL_TERM_OP_SHL                    41
#define SPI_SYMBOL_TERM_OP_SHR                    42
#define SPI_SYMBOL_TERM_OP_SHRR                   43
#define SPI_SYMBOL_TERM_OP_LT                     44
#define SPI_SYMBOL_TERM_OP_GT                     45
#define SPI_SYMBOL_TERM_OP_LE                     46
#define SPI_SYMBOL_TERM_OP_GE                     47
#define SPI_SYMBOL_TERM_INSTANCE_OF               48
#define SPI_SYMBOL_TERM_IN                        49
#define SPI_SYMBOL_TERM_OP_EQ                     50
#define SPI_SYMBOL_TERM_OP_NE                     51
#define SPI_SYMBOL_TERM_OP_TEQ                    52
#define SPI_SYMBOL_TERM_OP_TNE                    53
#define SPI_SYMBOL_TERM_OP_ASS_MUL                54
#define SPI_SYMBOL_TERM_OP_ASS_DIV                55
#define SPI_SYMBOL_TERM_OP_ASS_MOD                56
#define SPI_SYMBOL_TERM_OP_ASS_ADD                57
#define SPI_SYMBOL_TERM_OP_ASS_SUB                58
#define SPI_SYMBOL_TERM_OP_ASS_SHL                59
#define SPI_SYMBOL_TERM_OP_ASS_SHR                60
#define SPI_SYMBOL_TERM_OP_ASS_SHRR               61
#define SPI_SYMBOL_TERM_OP_ASS_AND                62
#define SPI_SYMBOL_TERM_OP_ASS_XOR                63
#define SPI_SYMBOL_TERM_OP_ASS_OR                 64
#define SPI_SYMBOL_TERM_NEW                       65
#define SPI_SYMBOL_TERM_LBRACK                    66
#define SPI_SYMBOL_TERM_RBRACK                    67
#define SPI_SYMBOL_TERM_DOT                       68
#define SPI_SYMBOL_TERM_REGULAR_EXPRESSION        69
#define SPI_SYMBOL_TERM_SWITCH                    70
#define SPI_SYMBOL_TERM_CASE                      71
#define SPI_SYMBOL_TERM_DEFAULT                   72
#define SPI_SYMBOL_TERM_DO                        73
#define SPI_SYMBOL_TERM_WHILE                     74
#define SPI_SYMBOL_TERM_WITH                      75
#define SPI_SYMBOL_TERM_CONTINUE                  76
#define SPI_SYMBOL_TERM_BREAK                     77
#define SPI_SYMBOL_TERM_THROW                     78
#define SPI_SYMBOL_TERM_TRY                       79
#define SPI_SYMBOL_TERM_CATCH                     80
#define SPI_SYMBOL_TERM_FINALLY                   81
#define SPI_SYMBOL_TERMINAL_COUNT 82

/* non terminals */
#define SPI_SYMBOL_NONTERM_$START                                0
#define SPI_SYMBOL_NONTERM_PROG                                  1
#define SPI_SYMBOL_NONTERM_TOP_STATEMENTS                        2
#define SPI_SYMBOL_NONTERM_TOP_STATEMENTS_PREFIX                 3
#define SPI_SYMBOL_NONTERM_TOP_STATEMENT                         4
#define SPI_SYMBOL_NONTERM_PRIMARY_EXPRESSION                    5
#define SPI_SYMBOL_NONTERM_SIMPLE_EXPRESSION                     6
#define SPI_SYMBOL_NONTERM_PARENTHESIZED_EXPRESSION              7
#define SPI_SYMBOL_NONTERM_FUNCTION_EXPRESSION                   8
#define SPI_SYMBOL_NONTERM_OBJECT_LITERAL                        9
#define SPI_SYMBOL_NONTERM_FIELD_LIST                            10
#define SPI_SYMBOL_NONTERM_LITERAL_FIELD                         11
#define SPI_SYMBOL_NONTERM_ARRAY_LITERAL                         12
#define SPI_SYMBOL_NONTERM_ELEMENT_LIST                          13
#define SPI_SYMBOL_NONTERM_LITERAL_ELEMENT                       14
#define SPI_SYMBOL_NONTERM_LEFT_SIDE_EXPRESSION                  15
#define SPI_SYMBOL_NONTERM_CALL_EXPRESSION                       16
#define SPI_SYMBOL_NONTERM_FULL_NEW_EXPRESSION                   17
#define SPI_SYMBOL_NONTERM_SHORT_NEW_EXPRESSION                  18
#define SPI_SYMBOL_NONTERM_FULL_NEW_SUBEXPRESSION                19
#define SPI_SYMBOL_NONTERM_SHORT_NEW_SUBEXPRESSION               20
#define SPI_SYMBOL_NONTERM_MEMBER_OPERATOR                       21
#define SPI_SYMBOL_NONTERM_ARGUMENTS                             22
#define SPI_SYMBOL_NONTERM_ARGUMENT_LIST                         23
#define SPI_SYMBOL_NONTERM_POSTFIX_EXPRESSION                    24
#define SPI_SYMBOL_NONTERM_UNARY_EXPRESSION                      25
#define SPI_SYMBOL_NONTERM_MULTIPLICATIVE_EXPRESSION             26
#define SPI_SYMBOL_NONTERM_ADDITIVE_EXPRESSION                   27
#define SPI_SYMBOL_NONTERM_SHIFT_EXPRESSION                      28
#define SPI_SYMBOL_NONTERM_RELATIONAL_EXPRESSION                 29
#define SPI_SYMBOL_NONTERM_EQUALITY_EXPRESSION                   30
#define SPI_SYMBOL_NONTERM_BITWISE_AND_EXPRESSION                31
#define SPI_SYMBOL_NONTERM_BITWISE_XOR_EXPRESSION                32
#define SPI_SYMBOL_NONTERM_BITWISE_OR_EXPRESSION                 33
#define SPI_SYMBOL_NONTERM_LOGICAL_AND_EXPRESSION                34
#define SPI_SYMBOL_NONTERM_LOGICAL_OR_EXPRESSION                 35
#define SPI_SYMBOL_NONTERM_CONDITIONAL_EXPRESSION                36
#define SPI_SYMBOL_NONTERM_ASSIGNMENT_EXPRESSION                 37
#define SPI_SYMBOL_NONTERM_COMPOUND_ASSIGNMENT                   38
#define SPI_SYMBOL_NONTERM_EXPRESSION                            39
#define SPI_SYMBOL_NONTERM_OPTIONAL_EXPRESSION                   40
#define SPI_SYMBOL_NONTERM_STATEMENT                             41
#define SPI_SYMBOL_NONTERM_EMPTY_STATEMENT                       42
#define SPI_SYMBOL_NONTERM_EXPRESSION_STATEMENT                  43
#define SPI_SYMBOL_NONTERM_VARIABLE_DEFINITION                   44
#define SPI_SYMBOL_NONTERM_VARIABLE_DECLARATION_LIST             45
#define SPI_SYMBOL_NONTERM_VARIABLE_DECLARATION                  46
#define SPI_SYMBOL_NONTERM_VARIABLE_INITIALIZER                  47
#define SPI_SYMBOL_NONTERM_BLOCK                                 48
#define SPI_SYMBOL_NONTERM_BLOCK_STATEMENTS                      49
#define SPI_SYMBOL_NONTERM_BLOCK_STATEMENTS_PREFIX               50
#define SPI_SYMBOL_NONTERM_LABELED_STATEMENT                     51
#define SPI_SYMBOL_NONTERM_IF_STATEMENT                          52
#define SPI_SYMBOL_NONTERM_SWITCH_STATEMENT                      53
#define SPI_SYMBOL_NONTERM_CASE_GROUPS                           54
#define SPI_SYMBOL_NONTERM_CASE_GROUP                            55
#define SPI_SYMBOL_NONTERM_LAST_CASE_GROUP                       56
#define SPI_SYMBOL_NONTERM_CASE_GUARDS                           57
#define SPI_SYMBOL_NONTERM_CASE_GUARD                            58
#define SPI_SYMBOL_NONTERM_DO_STATEMENT                          59
#define SPI_SYMBOL_NONTERM_WHILE_STATEMENT                       60
#define SPI_SYMBOL_NONTERM_FOR_STATEMENT                         61
#define SPI_SYMBOL_NONTERM_FOR_INITIALIZER                       62
#define SPI_SYMBOL_NONTERM_FOR_IN_BINDING                        63
#define SPI_SYMBOL_NONTERM_WITH_STATEMENT                        64
#define SPI_SYMBOL_NONTERM_CONTINUE_STATEMENT                    65
#define SPI_SYMBOL_NONTERM_BREAK_STATEMENT                       66
#define SPI_SYMBOL_NONTERM_OPTIONAL_LABEL                        67
#define SPI_SYMBOL_NONTERM_RETURN_STATEMENT                      68
#define SPI_SYMBOL_NONTERM_THROW_STATEMENT                       69
#define SPI_SYMBOL_NONTERM_TRY_STATEMENT                         70
#define SPI_SYMBOL_NONTERM_CATCH_CLAUSES                         71
#define SPI_SYMBOL_NONTERM_CATCH_CLAUSE                          72
#define SPI_SYMBOL_NONTERM_FINALLY_CLAUSE                        73
#define SPI_SYMBOL_NONTERM_FUNCTION_DEFINITION                   74
#define SPI_SYMBOL_NONTERM_ANONYMOUS_FUNCTION                    75
#define SPI_SYMBOL_NONTERM_NAMED_FUNCTION                        76
#define SPI_SYMBOL_NONTERM_FORMAL_PARAMETERS_AND_BODY            77
#define SPI_SYMBOL_NONTERM_FORMAL_PARAMETERS                     78
#define SPI_SYMBOL_NONTERM_FORMAL_PARAMETERS_PREFIX              79
#define SPI_SYMBOL_NONTERM_FORMAL_PARAMETER                      80
#define SPI_SYMBOL_NONTERM_OPTIONAL_SEMICOLON                    81
#endif /* SPISYMBOL_H */
