/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GROASTFILE_H_
#define GROASTFILE_H_

#include <grossruntime.h>
#include "groastlines.h"

G_BEGIN_DECLS

#define GROAST_TYPE_FILE              (groast_file_get_type())
#define GROAST_FILE(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_file_get_type(), GroAstFile))
#define GROAST_FILE_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_FILE, GroAstFileClass))
#define GROAST_IS_FILE(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_FILE))
#define GROAST_IS_FILE_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_FILE))
#define GROAST_FILE_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_FILE, GroAstFileClass))


typedef struct _GroAstFile               GroAstFile;
typedef struct _GroAstFilePrivate        GroAstFilePrivate;
typedef struct _GroAstFileClass          GroAstFileClass;


struct _GroAstFile {
	GObject parent;
};

struct _GroAstFileClass {
	GObjectClass parent_class;
};


GType groast_file_get_type();

GroAstFile *groast_file_new_1(GroRunIToken *ast_lines);
GroRunIToken *groast_file_tk_ast_lines(GroAstFile *self);
GroAstLines *groast_file_get_ast_lines(GroAstFile *self);

G_END_DECLS

#endif /* GROASTFILE_H_ */
