/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "groastline.h"

struct _GroAstLinePrivate {
	GroRunIToken *line_body;
	GroRunIToken *name;
};


G_DEFINE_TYPE_WITH_CODE(GroAstLine, groast_line, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstLine)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void groast_line_class_init(GroAstLineClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_line_init(GroAstLine *instance) {
}

static void l_dispose(GObject *object) {
	GroAstLine *instance = groast_line(object);
	GroAstLinePrivate *priv = groast_line_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->line_body);
	L_SAFE_UNREF_PTR(priv->name);
	G_OBJECT_CLASS(groast_line_parent_class)->dispose(object);
}

GroAstLine *groast_line_new_1(GroRunIToken *name, GroRunIToken *line_body) {
	GroAstLine *instance = g_object_new(GROAST_TYPE_LINE, NULL);
	GroAstLinePrivate *priv = groast_line_get_instance_private(instance);
	priv->line_body = g_object_ref(line_body);
	priv->name = g_object_ref(name);
	return instance;
}

GroAstLine *groast_line_new_2(GroRunIToken *name) {
	GroAstLine *instance = g_object_new(GROAST_TYPE_LINE, NULL);
	GroAstLinePrivate *priv = groast_line_get_instance_private(instance);
	priv->line_body = NULL;
	priv->name = g_object_ref(name);
	return instance;
}

GroRunIToken *groast_line_tk_line_body(GroAstLine *self) {
	GroAstLinePrivate *priv = groast_line_get_instance_private(self);
	return priv->line_body;
}

GroAstLineBody *groast_line_get_line_body(GroAstLine *self) {
	GroAstLinePrivate *priv = groast_line_get_instance_private(self);
	return (GroAstLineBody *) grorun_itoken_get_value(priv->line_body);
}

GroRunIToken *groast_line_tk_name(GroAstLine *self) {
	GroAstLinePrivate *priv = groast_line_get_instance_private(self);
	return priv->name;
}

CatStringWo *groast_line_get_name(GroAstLine *self) {
	GroAstLinePrivate *priv = groast_line_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->name);
}

