/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "groastfile.h"

struct _GroAstFilePrivate {
	GroRunIToken *ast_lines;
};


G_DEFINE_TYPE_WITH_CODE(GroAstFile, groast_file, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstFile)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void groast_file_class_init(GroAstFileClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_file_init(GroAstFile *instance) {
}

static void l_dispose(GObject *object) {
	GroAstFile *instance = groast_file(object);
	GroAstFilePrivate *priv = groast_file_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ast_lines);
	G_OBJECT_CLASS(groast_file_parent_class)->dispose(object);
}

GroAstFile *groast_file_new_1(GroRunIToken *ast_lines) {
	GroAstFile *instance = g_object_new(GROAST_TYPE_FILE, NULL);
	GroAstFilePrivate *priv = groast_file_get_instance_private(instance);
	priv->ast_lines = g_object_ref(ast_lines);
	return instance;
}

GroRunIToken *groast_file_tk_ast_lines(GroAstFile *self) {
	GroAstFilePrivate *priv = groast_file_get_instance_private(self);
	return priv->ast_lines;
}

GroAstLines *groast_file_get_ast_lines(GroAstFile *self) {
	GroAstFilePrivate *priv = groast_file_get_instance_private(self);
	return (GroAstLines *) grorun_itoken_get_value(priv->ast_lines);
}

