/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GROASTLINE_H_
#define GROASTLINE_H_

#include "catstringwo.h"
#include "catstringwo.h"
#include <grossruntime.h>
#include "groastlinebody.h"

G_BEGIN_DECLS

#define GROAST_TYPE_LINE              (groast_line_get_type())
#define GROAST_LINE(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_line_get_type(), GroAstLine))
#define GROAST_LINE_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_LINE, GroAstLineClass))
#define GROAST_IS_LINE(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_LINE))
#define GROAST_IS_LINE_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_LINE))
#define GROAST_LINE_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_LINE, GroAstLineClass))


typedef struct _GroAstLine               GroAstLine;
typedef struct _GroAstLinePrivate        GroAstLinePrivate;
typedef struct _GroAstLineClass          GroAstLineClass;


struct _GroAstLine {
	GObject parent;
};

struct _GroAstLineClass {
	GObjectClass parent_class;
};


GType groast_line_get_type();

GroAstLine *groast_line_new_1(GroRunIToken *name, GroRunIToken *line_body);
GroAstLine *groast_line_new_2(GroRunIToken *name);
GroRunIToken *groast_line_tk_line_body(GroAstLine *self);
GroAstLineBody *groast_line_get_line_body(GroAstLine *self);
GroRunIToken *groast_line_tk_name(GroAstLine *self);
CatStringWo *groast_line_get_name(GroAstLine *self);

G_END_DECLS

#endif /* GROASTLINE_H_ */
