/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GROASTTYPE_DESCRIPTION_H_
#define GROASTTYPE_DESCRIPTION_H_

#include <grossruntime.h>
#include "catstringwo.h"
#include "catstringwo.h"

G_BEGIN_DECLS

#define GROAST_TYPE_TYPE_DESCRIPTION              (groast_type_description_get_type())
#define GROAST_TYPE_DESCRIPTION(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_type_description_get_type(), GroAstTypeDescription))
#define GROAST_TYPE_DESCRIPTION_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_TYPE_DESCRIPTION, GroAstTypeDescriptionClass))
#define GROAST_IS_TYPE_DESCRIPTION(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_TYPE_DESCRIPTION))
#define GROAST_IS_TYPE_DESCRIPTION_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_TYPE_DESCRIPTION))
#define GROAST_TYPE_DESCRIPTION_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_TYPE_DESCRIPTION, GroAstTypeDescriptionClass))


typedef struct _GroAstTypeDescription               GroAstTypeDescription;
typedef struct _GroAstTypeDescriptionPrivate        GroAstTypeDescriptionPrivate;
typedef struct _GroAstTypeDescriptionClass          GroAstTypeDescriptionClass;


struct _GroAstTypeDescription {
	GObject parent;
};

struct _GroAstTypeDescriptionClass {
	GObjectClass parent_class;
};


GType groast_type_description_get_type();

GroAstTypeDescription *groast_type_description_new_1(GroRunIToken *description, GroRunIToken *opt_extends);
GroRunIToken *groast_type_description_tk_opt_extends(GroAstTypeDescription *self);
CatStringWo *groast_type_description_get_opt_extends(GroAstTypeDescription *self);
GroRunIToken *groast_type_description_tk_description(GroAstTypeDescription *self);
CatStringWo *groast_type_description_get_description(GroAstTypeDescription *self);

G_END_DECLS

#endif /* GROASTTYPE_DESCRIPTION_H_ */
