/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "groasttypedescription.h"

struct _GroAstTypeDescriptionPrivate {
	GroRunIToken *opt_extends;
	GroRunIToken *description;
};


G_DEFINE_TYPE_WITH_CODE(GroAstTypeDescription, groast_type_description, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstTypeDescription)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void groast_type_description_class_init(GroAstTypeDescriptionClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_type_description_init(GroAstTypeDescription *instance) {
}

static void l_dispose(GObject *object) {
	GroAstTypeDescription *instance = groast_type_description(object);
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->opt_extends);
	L_SAFE_UNREF_PTR(priv->description);
	G_OBJECT_CLASS(groast_type_description_parent_class)->dispose(object);
}

GroAstTypeDescription *groast_type_description_new_1(GroRunIToken *description, GroRunIToken *opt_extends) {
	GroAstTypeDescription *instance = g_object_new(GROAST_TYPE_TYPE_DESCRIPTION, NULL);
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(instance);
	priv->opt_extends = g_object_ref(opt_extends);
	priv->description = g_object_ref(description);
	return instance;
}

GroRunIToken *groast_type_description_tk_opt_extends(GroAstTypeDescription *self) {
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(self);
	return priv->opt_extends;
}

CatStringWo *groast_type_description_get_opt_extends(GroAstTypeDescription *self) {
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->opt_extends);
}

GroRunIToken *groast_type_description_tk_description(GroAstTypeDescription *self) {
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(self);
	return priv->description;
}

CatStringWo *groast_type_description_get_description(GroAstTypeDescription *self) {
	GroAstTypeDescriptionPrivate *priv = groast_type_description_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->description);
}

