/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "groastlinebody.h"

struct _GroAstLineBodyPrivate {
	GroRunIToken *statement;
};


G_DEFINE_TYPE_WITH_CODE(GroAstLineBody, groast_line_body, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstLineBody)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void groast_line_body_class_init(GroAstLineBodyClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_line_body_init(GroAstLineBody *instance) {
}

static void l_dispose(GObject *object) {
	GroAstLineBody *instance = groast_line_body(object);
	GroAstLineBodyPrivate *priv = groast_line_body_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->statement);
	G_OBJECT_CLASS(groast_line_body_parent_class)->dispose(object);
}

GroAstLineBody *groast_line_body_new_1(GroRunIToken *statement) {
	GroAstLineBody *instance = g_object_new(GROAST_TYPE_LINE_BODY, NULL);
	GroAstLineBodyPrivate *priv = groast_line_body_get_instance_private(instance);
	priv->statement = g_object_ref(statement);
	return instance;
}

GroRunIToken *groast_line_body_tk_statement(GroAstLineBody *self) {
	GroAstLineBodyPrivate *priv = groast_line_body_get_instance_private(self);
	return priv->statement;
}

GroAstTypeDescription *groast_line_body_get_statement(GroAstLineBody *self) {
	GroAstLineBodyPrivate *priv = groast_line_body_get_instance_private(self);
	return (GroAstTypeDescription *) grorun_itoken_get_value(priv->statement);
}

