/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GROASTLINES_H_
#define GROASTLINES_H_

#include "groastline.h"
#include "groastline.h"
#include <grossruntime.h>

G_BEGIN_DECLS

#define GROAST_TYPE_LINES              (groast_lines_get_type())
#define GROAST_LINES(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_lines_get_type(), GroAstLines))
#define GROAST_LINES_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_LINES, GroAstLinesClass))
#define GROAST_IS_LINES(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_LINES))
#define GROAST_IS_LINES_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_LINES))
#define GROAST_LINES_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_LINES, GroAstLinesClass))


typedef struct _GroAstLines               GroAstLines;
typedef struct _GroAstLinesPrivate        GroAstLinesPrivate;
typedef struct _GroAstLinesClass          GroAstLinesClass;


struct _GroAstLines {
	GObject parent;
};

struct _GroAstLinesClass {
	GObjectClass parent_class;
};


GType groast_lines_get_type();

GroAstLines *groast_lines_new_1(GroRunIToken *ast_lines, GroRunIToken *ast_line);
GroAstLines *groast_lines_new_2(GroRunIToken *ast_line);
GroRunIToken *groast_lines_tk_ast_lines(GroAstLines *self);
GroAstLines *groast_lines_get_ast_lines(GroAstLines *self);
GroRunIToken *groast_lines_tk_ast_line(GroAstLines *self);
GroAstLine *groast_lines_get_ast_line(GroAstLines *self);

G_END_DECLS

#endif /* GROASTLINES_H_ */
