/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GRTASTAST_ACTIONS_H_
#define GRTASTAST_ACTIONS_H_

#include <grossruntime.h>
#include "groastlines.h"
#include "groasttypedescription.h"
#include "groastline.h"
#include "groastlinebody.h"
#include "groastfile.h"

G_BEGIN_DECLS

#define GRTAST_TYPE_AST_ACTIONS              (grtast_ast_actions_get_type())
#define GRTAST_AST_ACTIONS(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), grtast_ast_actions_get_type(), GrtAstAstActions))
#define GRTAST_AST_ACTIONS_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GRTAST_TYPE_AST_ACTIONS, GrtAstAstActionsClass))
#define GRTAST_IS_AST_ACTIONS(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRTAST_TYPE_AST_ACTIONS))
#define GRTAST_IS_AST_ACTIONS_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GRTAST_TYPE_AST_ACTIONS))
#define GRTAST_AST_ACTIONS_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GRTAST_TYPE_AST_ACTIONS, GrtAstAstActionsClass))


typedef struct _GrtAstAstActions               GrtAstAstActions;
typedef struct _GrtAstAstActionsClass          GrtAstAstActionsClass;


struct _GrtAstAstActions {
	GObject parent;
};

struct _GrtAstAstActionsClass {
	GObjectClass parent_class;
};


GType grtast_ast_actions_get_type();


G_END_DECLS

#endif /* GRTASTAST_ACTIONS_H_ */
