/* This file was generated by Gross-CC on 2016.11.24 AD at 13:25:16 CET */
#include "null.h"

struct _CatStringWoPrivate {
	GroRunIToken *extendsTypeName;
};


G_DEFINE_TYPE_WITH_CODE(CatStringWo, cat_string_wo, G_TYPE_OBJECT,
		G_ADD_PRIVATE(CatStringWo)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; g_object_unref(ptr); }

static void l_dispose(GObject *object);

static void cat_string_wo_class_init(CatStringWoClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void cat_string_wo_init(CatStringWo *instance) {
}

static void l_dispose(GObject *object) {
	CatStringWo *instance = cat_string_wo(object);
	CatStringWoPrivate *priv = cat_string_wo_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->extendsTypeName);
	G_OBJECT_CLASS(cat_string_wo_parent_class)->dispose(object);
}

CatStringWo *cat_string_wo_new_1(GroRunIToken *extendsTypeName) {
	CatStringWo *instance = g_object_new(CAT_TYPE_STRING_WO, NULL);
	CatStringWoPrivate *priv = cat_string_wo_get_instance_private(instance);
	priv->extendsTypeName = g_object_ref(extendsTypeName);
	return instance;
}

GroRunIToken *cat_string_wo_tk_extendsTypeName(CatStringWo *self) {
	CatStringWoPrivate *priv = cat_string_wo_get_instance_private(self);
	return priv->extendsTypeName;
}

CatStringWo *cat_string_wo_get_extendsTypeName(CatStringWo *self) {
	CatStringWoPrivate *priv = cat_string_wo_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->extendsTypeName);
}

