/* This file was generated by Gross-CC on 2016.11.24 AD at 13:25:16 CET */
#ifndef CATSTRING_WO_H_
#define CATSTRING_WO_H_

#include <grossruntime.h>

G_BEGIN_DECLS

#define CAT_TYPE_STRING_WO              (cat_string_wo_get_type())
#define CAT_STRING_WO(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), cat_string_wo_get_type(), CatStringWo))
#define CAT_STRING_WO_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), CAT_TYPE_STRING_WO, CatStringWoClass))
#define CAT_IS_STRING_WO(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAT_TYPE_STRING_WO))
#define CAT_IS_STRING_WO_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), CAT_TYPE_STRING_WO))
#define CAT_STRING_WO_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), CAT_TYPE_STRING_WO, CatStringWoClass))


typedef struct _CatStringWo               CatStringWo;
typedef struct _CatStringWoPrivate        CatStringWoPrivate;
typedef struct _CatStringWoClass          CatStringWoClass;


struct _CatStringWo {
	GObject parent;
};

struct _CatStringWoClass {
	GObjectClass parent_class;
};


GType cat_string_wo_get_type();

CatStringWo *cat_string_wo_new_1(GroRunIToken *extendsTypeName);
GroRunIToken *cat_string_wo_tk_extendsTypeName(CatStringWo *self);
CatStringWo *cat_string_wo_get_extendsTypeName(CatStringWo *self);

G_END_DECLS

#endif /* CATSTRING_WO_H_ */
