/* This file was generated by Gross-CC on 2017.01.25 AD at 22:48:06 CET */
#ifndef MULRUSTACTIONS_H_
#define MULRUSTACTIONS_H_

#include <caterpillar.h>

G_BEGIN_DECLS

#define MULRUST_TYPE_ACTIONS              (mulrust_actions_get_type())
#define MULRUST_ACTIONS(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), mulrust_actions_get_type(), MulRustActions))
#define MULRUST_ACTIONS_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), MULRUST_TYPE_ACTIONS, MulRustActionsClass))
#define MULRUST_IS_ACTIONS(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MULRUST_TYPE_ACTIONS))
#define MULRUST_IS_ACTIONS_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), MULRUST_TYPE_ACTIONS))
#define MULRUST_ACTIONS_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), MULRUST_TYPE_ACTIONS, MulRustActionsClass))


typedef struct _MulRustActions               MulRustActions;
typedef struct _MulRustActionsPrivate        MulRustActionsPrivate;
typedef struct _MulRustActionsClass          MulRustActionsClass;


struct _MulRustActions {
	GObject parent;
};

struct _MulRustActionsClass {
	GObjectClass parent_class;
};


GType mulrust_actions_get_type();

MulRustActions *mulrust_actions_new();

G_END_DECLS

#endif /* MULRUSTACTIONS_H_ */
