/* This file was generated by Gross-CC on 2017.03.09 AD at 21:10:09 CET */
#ifndef JAGASTGOAL_H_
#define JAGASTGOAL_H_

#include "grorunfork.h"

G_BEGIN_DECLS

#define JAGAST_TYPE_GOAL              (jagast_goal_get_type())
#define JAGAST_GOAL(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), jagast_goal_get_type(), JagAstgoal))
#define JAGAST_GOAL_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), JAGAST_TYPE_GOAL, JagAstgoalClass))
#define JAGAST_IS_GOAL(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JAGAST_TYPE_GOAL))
#define JAGAST_IS_GOAL_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), JAGAST_TYPE_GOAL))
#define JAGAST_GOAL_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), JAGAST_TYPE_GOAL, JagAstgoalClass))


typedef struct _JagAstgoal               JagAstgoal;
typedef struct _JagAstgoalClass          JagAstgoalClass;


struct _JagAstgoal {
	GObject parent;
};

struct _JagAstgoalClass {
	GObjectClass parent_class;
};


GType jagast_goal_get_type();

JagAstgoal *jagast_goal_new_1();

G_END_DECLS

#endif /* JAGASTGOAL_H_ */
