/* This file was generated by Gross-CC on 2016.11.25 AD at 13:38:25 CET */
#ifndef GROACTIONS_H_
#define GROACTIONS_H_

#include <caterpillar.h>

G_BEGIN_DECLS

#define GRO_TYPE_ACTIONS              (gro_actions_get_type())
#define GRO_ACTIONS(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), gro_actions_get_type(), GroActions))
#define GRO_ACTIONS_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GRO_TYPE_ACTIONS, GroActionsClass))
#define GRO_IS_ACTIONS(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRO_TYPE_ACTIONS))
#define GRO_IS_ACTIONS_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GRO_TYPE_ACTIONS))
#define GRO_ACTIONS_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GRO_TYPE_ACTIONS, GroActionsClass))


typedef struct _GroActions               GroActions;
typedef struct _GroActionsPrivate        GroActionsPrivate;
typedef struct _GroActionsClass          GroActionsClass;


struct _GroActions {
	GObject parent;
};

struct _GroActionsClass {
	GObjectClass parent_class;
};


GType gro_actions_get_type();

GroActions *gro_actions_new();

G_END_DECLS

#endif /* GROACTIONS_H_ */
