/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#ifndef GRTASTACTIONS_H_
#define GRTASTACTIONS_H_

#include <caterpillar.h>

G_BEGIN_DECLS

#define GRTAST_TYPE_ACTIONS              (grtast_actions_get_type())
#define GRTAST_ACTIONS(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), grtast_actions_get_type(), GrtAstActions))
#define GRTAST_ACTIONS_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GRTAST_TYPE_ACTIONS, GrtAstActionsClass))
#define GRTAST_IS_ACTIONS(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRTAST_TYPE_ACTIONS))
#define GRTAST_IS_ACTIONS_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GRTAST_TYPE_ACTIONS))
#define GRTAST_ACTIONS_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GRTAST_TYPE_ACTIONS, GrtAstActionsClass))


typedef struct _GrtAstActions               GrtAstActions;
typedef struct _GrtAstActionsPrivate        GrtAstActionsPrivate;
typedef struct _GrtAstActionsClass          GrtAstActionsClass;


struct _GrtAstActions {
	GObject parent;
};

struct _GrtAstActionsClass {
	GObjectClass parent_class;
};


GType grtast_actions_get_type();

GrtAstActions *grtast_actions_new();

G_END_DECLS

#endif /* GRTASTACTIONS_H_ */
