/* This file was generated by Gross-CC on 2016.11.24 AD at 16:57:46 CET */
#include "grtastactions.h"
#include <grossruntime.h>


import net.natpad.gross.ast.bnf.*;



#include <logging/catlogdefs.h>
#define CAT_LOG_LEVEL CAT_LOG_WARN
#define CAT_LOG_CLAZZ "GrtAstActions"
#include <logging/catlog.h>

static void l_action_handler_iface_init(GroRunIActionHandlerInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GrtAstActions, grtast_actions, G_TYPE_OBJECT,
		G_IMPLEMENT_INTERFACE(GRORUN_TYPE_IACTION_HANDLER, l_action_handler_iface_init)
);

static void l_finalize(GObject *object);
static void grtast_actions_class_init(GrtAstActionsClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->finalize = l_finalize;
}
static void grtast_actions_init(GrtAstActions *instance) {
}
static void l_finalize(GObject *object) {
	cat_log_detail("finalize:%p", object);
	cat_ref_denounce(object);
	G_OBJECT_CLASS(grtast_actions_parent_class)->finalize(object);
	cat_log_detail("finalized:%p", object);
}
GrtAstActions *grtast_actions_new() {
	GrtAstActions *result = g_object_new(GRTAST_TYPE_ACTIONS, NULL);
	cat_ref_anounce(result);
	return result;
}

static GroRunStackEntry *l_extract(GroRunFork *fork, GroRunReduceLayout *reduce_layout, int offset) {
	int rloff = grorun_reduce_layout_calculate_stack_offset(reduce_layout, offset);
	return  grorun_fork_get_entry(fork, rloff);
}


static GObject *l_run_action(GroRunIActionHandler *self, GroRunFork *fork, GroRunReduceLayout *reduce_layout, int action_id) {
	void *result = NULL;
	switch(action_id) {
		case 0 : { /* spec ⟶ ast_lines:ast_lines */
				GroRunStackEntry *gse_ast_lines = l_extract(fork, reduce_layout, 0);
				AstLines *ast_lines = grorun_stack_entry_get_value(gse_ast_lines);
				result = new AstFile(ast_lines); 
		} break;
		case 1 : { /* ast_lines ⟶ ast_line:ast_line */
				GroRunStackEntry *gse_ast_line = l_extract(fork, reduce_layout, 0);
				AstLine *ast_line = grorun_stack_entry_get_value(gse_ast_line);
				result = new AstLines(null, ast_line); 
		} break;
		case 2 : { /* ast_lines ⟶ ast_lines:ast_lines ast_line:ast_line */
				GroRunStackEntry *gse_ast_lines = l_extract(fork, reduce_layout, 0);
				AstLines *ast_lines = grorun_stack_entry_get_value(gse_ast_lines);
				GroRunStackEntry *gse_ast_line = l_extract(fork, reduce_layout, 1);
				AstLine *ast_line = grorun_stack_entry_get_value(gse_ast_line);
				result = new AstLines(ast_lines, ast_line); 
		} break;
		case 3 : { /* ast_line ⟶ IDENTIFIER:name FORWARD */
				GroRunStackEntry *gse_name = l_extract(fork, reduce_layout, 0);
				String *name = grorun_stack_entry_get_value(gse_name);
				result = new AstLine(name, new LineBody()); 
		} break;
		case 4 : { /* line_body ⟶ type_description:statement */
				GroRunStackEntry *gse_statement = l_extract(fork, reduce_layout, 0);
				TypeDescription *statement = grorun_stack_entry_get_value(gse_statement);
				result = new LineBody(statement); 
		} break;
		case 5 : { /* ast_line ⟶ IDENTIFIER:name LCUBRACK line_body:line_body RCUBRACK */
				GroRunStackEntry *gse_name = l_extract(fork, reduce_layout, 0);
				String *name = grorun_stack_entry_get_value(gse_name);
				GroRunStackEntry *gse_line_body = l_extract(fork, reduce_layout, 2);
				LineBody *line_body = grorun_stack_entry_get_value(gse_line_body);
				result = new AstLine(name, line_body); 
		} break;
		case 6 : { /* type_description ⟶ TYPE STRING:description opt_extends:opt_extends SEMI */
				GroRunStackEntry *gse_description = l_extract(fork, reduce_layout, 1);
				String *description = grorun_stack_entry_get_value(gse_description);
				GroRunStackEntry *gse_opt_extends = l_extract(fork, reduce_layout, 2);
				String *opt_extends = grorun_stack_entry_get_value(gse_opt_extends);
				result = new TypeDescription(description, opt_extends); 
		} break;
		case 7 : { /* opt_extends ⟶ EXTENDS STRING:extendsTypeName */
				GroRunStackEntry *gse_extendsTypeName = l_extract(fork, reduce_layout, 1);
				String *extendsTypeName = grorun_stack_entry_get_value(gse_extendsTypeName);
				result = extendsTypeName; 
		} break;
	}
	return (GObject *) result;
}

static void l_action_handler_iface_init(GroRunIActionHandlerInterface *iface) {
	iface->runAction = l_run_action;
}
