/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastrhsrulelist.h"
#include "../../src/ast/groastirhsenlistable.h"

struct _GroAstRhsRuleListPrivate {
	GroRunIToken *ruleList;
	GroRunIToken *rule;
};

static void l_irhs_enlistable_iface_init(GroAstIRhsEnlistableInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GroAstRhsRuleList, groast_rhs_rule_list, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstRhsRuleList)
		G_IMPLEMENT_INTERFACE(GROAST_TYPE_IRHS_ENLISTABLE, l_irhs_enlistable_iface_init)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_rhs_rule_list_class_init(GroAstRhsRuleListClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_rhs_rule_list_init(GroAstRhsRuleList *instance) {
}

static void l_dispose(GObject *object) {
	GroAstRhsRuleList *instance = GROAST_RHS_RULE_LIST(object);
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ruleList);
	L_SAFE_UNREF_PTR(priv->rule);
	G_OBJECT_CLASS(groast_rhs_rule_list_parent_class)->dispose(object);
}

CatArrayWo *groast_rhs_rule_list_enlist(GroAstRhsRuleList *self) {
 
	CatArrayWo *result = cat_array_wo_new();
	GroAstRhsRuleList *tdl = self;
	while(tdl) {
		GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(tdl);
		cat_array_wo_append(result, (GObject *) priv->rule);
		if (priv->ruleList==NULL) {
			break;
		}
		tdl = (GroAstRhsRuleList *) grorun_itoken_get_value(priv->ruleList);
	}
	cat_array_wo_reverse(result);
	return result;
  
}

GroAstRhsRuleList *groast_rhs_rule_list_new_1(GroRunIToken *ruleList, GroRunIToken *rule) {
	GroAstRhsRuleList *instance = g_object_new(GROAST_TYPE_RHS_RULE_LIST, NULL);
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(instance);
	priv->ruleList = L_SAFE_REF_PTR(ruleList);
	priv->rule = L_SAFE_REF_PTR(rule);
	return instance;
}

GroAstRhsRuleList *groast_rhs_rule_list_new_2(GroRunIToken *rule) {
	GroAstRhsRuleList *instance = g_object_new(GROAST_TYPE_RHS_RULE_LIST, NULL);
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(instance);
	priv->ruleList = NULL;
	priv->rule = L_SAFE_REF_PTR(rule);
	return instance;
}

GroRunIToken *groast_rhs_rule_list_tk_ruleList(GroAstRhsRuleList *self) {
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(self);
	return priv->ruleList;
}

GroAstRhsRuleList *groast_rhs_rule_list_get_ruleList(GroAstRhsRuleList *self) {
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(self);
	return (GroAstRhsRuleList *) grorun_itoken_get_value(priv->ruleList);
}

GroRunIToken *groast_rhs_rule_list_tk_rule(GroAstRhsRuleList *self) {
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(self);
	return priv->rule;
}

GroAstRhsRule *groast_rhs_rule_list_get_rule(GroAstRhsRuleList *self) {
	GroAstRhsRuleListPrivate *priv = groast_rhs_rule_list_get_instance_private(self);
	return (GroAstRhsRule *) grorun_itoken_get_value(priv->rule);
}


/******************** start GroAstIRhsEnlistable implementation  ********************/


static void l_irhs_enlistable_iface_init(GroAstIRhsEnlistableInterface *iface) {

  	iface->enlist = (GroAstEnlistFunc) groast_rhs_rule_list_enlist;
  
}

/******************** end GroAstIRhsEnlistable implementation ********************/

