/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastterminaldeclarationlist.h"

struct _GroAstTerminalDeclarationListPrivate {
	GroRunIToken *td;
	GroRunIToken *tdlist;
};


G_DEFINE_TYPE_WITH_CODE(GroAstTerminalDeclarationList, groast_terminal_declaration_list, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstTerminalDeclarationList)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_terminal_declaration_list_class_init(GroAstTerminalDeclarationListClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_terminal_declaration_list_init(GroAstTerminalDeclarationList *instance) {
}

static void l_dispose(GObject *object) {
	GroAstTerminalDeclarationList *instance = GROAST_TERMINAL_DECLARATION_LIST(object);
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->td);
	L_SAFE_UNREF_PTR(priv->tdlist);
	G_OBJECT_CLASS(groast_terminal_declaration_list_parent_class)->dispose(object);
}

CatArrayWo *groast_terminal_declaration_list_enlist(GroAstTerminalDeclarationList *self) {
 
	CatArrayWo *result = cat_array_wo_new();
	GroAstTerminalDeclarationList *tdl = self;
	while(tdl) {
		GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(tdl);
		cat_array_wo_append(result, (GObject *) priv->td);
		if (priv->tdlist==NULL) {
			break;
		}
		tdl = (GroAstTerminalDeclarationList *) grorun_itoken_get_value(priv->tdlist);
	}
	cat_array_wo_reverse(result);
	return result;
  
}

GroAstTerminalDeclarationList *groast_terminal_declaration_list_new_1(GroRunIToken *tdlist, GroRunIToken *td) {
	GroAstTerminalDeclarationList *instance = g_object_new(GROAST_TYPE_TERMINAL_DECLARATION_LIST, NULL);
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(instance);
	priv->td = L_SAFE_REF_PTR(td);
	priv->tdlist = L_SAFE_REF_PTR(tdlist);
	return instance;
}

GroRunIToken *groast_terminal_declaration_list_tk_td(GroAstTerminalDeclarationList *self) {
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(self);
	return priv->td;
}

GroAstTerminalDeclaration *groast_terminal_declaration_list_get_td(GroAstTerminalDeclarationList *self) {
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(self);
	return (GroAstTerminalDeclaration *) grorun_itoken_get_value(priv->td);
}

GroRunIToken *groast_terminal_declaration_list_tk_tdlist(GroAstTerminalDeclarationList *self) {
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(self);
	return priv->tdlist;
}

GroAstTerminalDeclarationList *groast_terminal_declaration_list_get_tdlist(GroAstTerminalDeclarationList *self) {
	GroAstTerminalDeclarationListPrivate *priv = groast_terminal_declaration_list_get_instance_private(self);
	return (GroAstTerminalDeclarationList *) grorun_itoken_get_value(priv->tdlist);
}

