/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastcodedefinition.h"

struct _GroAstCodeDefinitionPrivate {
	GroRunIToken *ruleRef;
	GroRunIToken *codeText;
};


G_DEFINE_TYPE_WITH_CODE(GroAstCodeDefinition, groast_code_definition, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstCodeDefinition)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_code_definition_class_init(GroAstCodeDefinitionClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_code_definition_init(GroAstCodeDefinition *instance) {
}

static void l_dispose(GObject *object) {
	GroAstCodeDefinition *instance = GROAST_CODE_DEFINITION(object);
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->ruleRef);
	L_SAFE_UNREF_PTR(priv->codeText);
	G_OBJECT_CLASS(groast_code_definition_parent_class)->dispose(object);
}

GroAstCodeDefinition *groast_code_definition_new_1(GroRunIToken *ruleRef, GroRunIToken *codeText) {
	GroAstCodeDefinition *instance = g_object_new(GROAST_TYPE_CODE_DEFINITION, NULL);
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(instance);
	priv->ruleRef = L_SAFE_REF_PTR(ruleRef);
	priv->codeText = L_SAFE_REF_PTR(codeText);
	return instance;
}

GroRunIToken *groast_code_definition_tk_ruleRef(GroAstCodeDefinition *self) {
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(self);
	return priv->ruleRef;
}

GroAstProdRuleRef *groast_code_definition_get_ruleRef(GroAstCodeDefinition *self) {
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(self);
	return (GroAstProdRuleRef *) grorun_itoken_get_value(priv->ruleRef);
}

GroRunIToken *groast_code_definition_tk_codeText(GroAstCodeDefinition *self) {
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(self);
	return priv->codeText;
}

CatStringWo *groast_code_definition_get_codeText(GroAstCodeDefinition *self) {
	GroAstCodeDefinitionPrivate *priv = groast_code_definition_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->codeText);
}

