/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastactions.h"
#include "groruniactionhandler.h"

static void l_iaction_handler_iface_init(GroRunIActionHandlerInterface *iface);

G_DEFINE_TYPE_WITH_CODE(GroAstActions, gro_ast_actions, G_TYPE_OBJECT,
		G_IMPLEMENT_INTERFACE(GRORUN_TYPE_IACTION_HANDLER, l_iaction_handler_iface_init)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void gro_ast_actions_class_init(GroAstActionsClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void gro_ast_actions_init(GroAstActions *instance) {
}

static void l_dispose(GObject *object) {
	G_OBJECT_CLASS(gro_ast_actions_parent_class)->dispose(object);
}

GroAstActions *gro_ast_actions_new() {
	GroAstActions *instance = g_object_new(GRO_TYPE_AST_ACTIONS, NULL);
	return instance;
}


/******************** start GroRunIActionHandler implementation  ********************/

static GroRunIToken *l_extract(GroRunFork *fork, GroRunReduceLayout *reduce_layout, int offset) {
	GroRunIToken *result = NULL;
	int rloff = grorun_reduce_layout_calculate_stack_offset(reduce_layout, offset);
	GroRunStackEntry *fe = grorun_fork_get_entry(fork, rloff);
	if (fe!=NULL) {
		result = grorun_stack_entry_get_lookahead(fe);
	}
	return result;
}


GObject *l_iaction_handler_run_action(GroRunIActionHandler *self, GroRunFork *fork, GroRunReduceLayout *reduce_layout, int action_id) {
	GObject *result = NULL;
	int prod_id = grorun_reduce_layout_get_production_id(reduce_layout);
	switch(prod_id) {

		case 22 : { // rhs_entry PLUS⇒rhs_entry_complete
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_unary_part_new_1(entry, GRO_AST_UN_PLUS);
		} break;

		case 23 : { // rhs_entry EXCL⇒rhs_entry_complete
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_unary_part_new_1(entry, GRO_AST_UN_EXCL);
		} break;

		case 12 : { // name rhs_rule_list SEMI⇒production
			GroRunIToken *lhsName = l_extract(fork, reduce_layout, 0);
			GroRunIToken *ruleList = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_production_definition_new_1(lhsName, ruleList);
		} break;

		case 42 : { // name INDEX_MARK NUMBER⇒prod_rule_ref
			GroRunIToken *lhsName = l_extract(fork, reduce_layout, 0);
			GroRunIToken *offset = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_prod_rule_ref_new_3(lhsName, offset);
		} break;

		case 2 : { // term_decl_list production_list⇒spec
			GroRunIToken *td = l_extract(fork, reduce_layout, 0);
			GroRunIToken *pl = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_spec_new_2(td, pl);
		} break;

		case 32 : { // rhs_entry_complete⇒rhs_sub
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_sub_new_2(entry);
		} break;

		case 29 : { // rhs_sub_list BAR rhs_sub⇒rhs_sub_list
			GroRunIToken *subList = l_extract(fork, reduce_layout, 0);
			GroRunIToken *sub = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_rhs_sub_list_new_1(subList, sub);
		} break;

		case 27 : { // COLON name⇒opt_label
			GroRunIToken *label = l_extract(fork, reduce_layout, 1);
			result = grorun_itoken_get_value(label);
			if (result) {g_object_ref(result); }
		} break;

		case 6 : { // TERMINAL ⊗ SEMI⇒term_decl
			result = (GObject *) groast_terminal_declaration_new_2();
		} break;

		case 5 : { // TERMINAL ids SEMI⇒term_decl
			GroRunIToken *ids = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_terminal_declaration_new_1(ids);
		} break;

		case 21 : { // rhs_entry STAR⇒rhs_entry_complete
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_unary_part_new_1(entry, GRO_AST_UN_STAR);
		} break;

		case 41 : { // name INDEX_MARK name⇒prod_rule_ref
			GroRunIToken *lhsName = l_extract(fork, reduce_layout, 0);
			GroRunIToken *label = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_prod_rule_ref_new_2(lhsName, label);
		} break;

		case 9 : { // IDENTIFIER⇒name
			GroRunIToken *id = l_extract(fork, reduce_layout, 0);
			result = grorun_itoken_get_value(id);
			if (result) {g_object_ref(result); }
		} break;

		case 37 : { // code_definition_list code_definition⇒code_definition_list
			GroRunIToken *cdList = l_extract(fork, reduce_layout, 0);
			GroRunIToken *codeDef = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_code_definition_list_new_1(cdList, codeDef);
		} break;

		case 19 : { // rhs_entry_complete⇒rhs_rule_part
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = grorun_itoken_get_value(entry);
			if (result) {g_object_ref(result); }
		} break;

		case 16 : { // INDEX_MARK name RULE_SEPERATOR rhs_rule_part_list⇒rhs_rule
			GroRunIToken *imark = l_extract(fork, reduce_layout, 1);
			GroRunIToken *rulePartList = l_extract(fork, reduce_layout, 3);
			result = (GObject *) groast_rhs_rule_new_2(imark, rulePartList);
		} break;

		case 1 : { // term_decl_list production_list imports_code type_definition_list code_definition_list⇒spec
			GroRunIToken *td = l_extract(fork, reduce_layout, 0);
			GroRunIToken *pl = l_extract(fork, reduce_layout, 1);
			GroRunIToken *im = l_extract(fork, reduce_layout, 2);
			GroRunIToken *tl = l_extract(fork, reduce_layout, 3);
			GroRunIToken *cl = l_extract(fork, reduce_layout, 4);
			result = (GObject *) groast_spec_new_1(td, pl, im, tl, cl);
		} break;

		case 8 : { // name⇒ids
			GroRunIToken *id = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_id_list_new_2(id);
		} break;

		case 40 : { // name⇒prod_rule_ref
			GroRunIToken *lhsName = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_prod_rule_ref_new_1(lhsName);
		} break;

		case 43 : { // CODE_TEXT⇒code_text
			GroRunIToken *ct = l_extract(fork, reduce_layout, 0);
			result = grorun_itoken_get_value(ct);
			if (result) {g_object_ref(result); }
		} break;

		case 3 : { // term_decl_list term_decl⇒term_decl_list
			GroRunIToken *tdlist = l_extract(fork, reduce_layout, 0);
			GroRunIToken *td = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_terminal_declaration_list_new_1(tdlist, td);
		} break;

		case 13 : { // rhs_rule_list rhs_rule⇒rhs_rule_list
			GroRunIToken *ruleList = l_extract(fork, reduce_layout, 0);
			GroRunIToken *rule = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_rhs_rule_list_new_1(ruleList, rule);
		} break;

		case 26 : { // name opt_label⇒rhs_entry
			GroRunIToken *symName = l_extract(fork, reduce_layout, 0);
			GroRunIToken *label = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_symbol_part_new_1(symName, label);
		} break;

		case 30 : { // rhs_sub⇒rhs_sub_list
			GroRunIToken *sub = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_sub_list_new_2(sub);
		} break;

		case 11 : { // production⇒production_list
			GroRunIToken *prod = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_production_definition_list_new_2(prod);
		} break;

		case 7 : { // ids COMMA name⇒ids
			GroRunIToken *ids = l_extract(fork, reduce_layout, 0);
			GroRunIToken *id = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_id_list_new_1(ids, id);
		} break;

		case 34 : { // type_definition_list type_definition⇒type_definition_list
			GroRunIToken *tdList = l_extract(fork, reduce_layout, 0);
			GroRunIToken *typeDef = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_type_definition_list_new_1(tdList, typeDef);
		} break;

		case 24 : { // LPAREN rhs_sub_list RPAREN⇒rhs_entry
			GroRunIToken *sub = l_extract(fork, reduce_layout, 1);
			result = grorun_itoken_get_value(sub);
			if (result) {g_object_ref(result); }
		} break;

		case 39 : { // CODE prod_rule_ref code_text⇒code_definition
			GroRunIToken *ruleRef = l_extract(fork, reduce_layout, 1);
			GroRunIToken *codeText = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_code_definition_new_1(ruleRef, codeText);
		} break;

		case 15 : { // RULE_SEPERATOR rhs_rule_part_list⇒rhs_rule
			GroRunIToken *rulePartList = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_rhs_rule_new_1(rulePartList);
		} break;

		case 20 : { // rhs_entry⇒rhs_entry_complete
			GroRunIToken *entry = l_extract(fork, reduce_layout, 0);
			result = grorun_itoken_get_value(entry);
			if (result) {g_object_ref(result); }
		} break;

		case 36 : { // TYPE name ids SEMI⇒type_definition
			GroRunIToken *symtype = l_extract(fork, reduce_layout, 1);
			GroRunIToken *symids = l_extract(fork, reduce_layout, 2);
			result = (GObject *) groast_type_definition_new_1(symtype, symids);
		} break;

		case 31 : { // rhs_sub rhs_entry_complete⇒rhs_sub
			GroRunIToken *sub = l_extract(fork, reduce_layout, 0);
			GroRunIToken *entry = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_rhs_sub_new_1(sub, entry);
		} break;

		case 33 : { // IMPORTS code_text⇒imports_code
			GroRunIToken *ct = l_extract(fork, reduce_layout, 1);
			result = grorun_itoken_get_value(ct);
			if (result) {g_object_ref(result); }
		} break;

		case 25 : { // LSQBRACK rhs_sub_list RSQBRACK⇒rhs_entry
			GroRunIToken *entry = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_rhs_unary_part_new_1(entry, GRO_AST_UN_EXCL);
		} break;

		case 10 : { // production_list production⇒production_list
			GroRunIToken *plist = l_extract(fork, reduce_layout, 0);
			GroRunIToken *prod = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_production_definition_list_new_1(plist, prod);
		} break;

		case 14 : { // rhs_rule⇒rhs_rule_list
			GroRunIToken *rule = l_extract(fork, reduce_layout, 0);
			result = (GObject *) groast_rhs_rule_list_new_2(rule);
		} break;

		case 17 : { // rhs_rule_part_list rhs_rule_part⇒rhs_rule_part_list
			GroRunIToken *rulePartList = l_extract(fork, reduce_layout, 0);
			GroRunIToken *rulePart = l_extract(fork, reduce_layout, 1);
			result = (GObject *) groast_rhs_rule_part_list_new_1(rulePartList, rulePart);
		} break;
	}
	return result;

}


static void l_iaction_handler_iface_init(GroRunIActionHandlerInterface *iface) {
	iface->runAction = l_iaction_handler_run_action;
}

/******************** end GroRunIActionHandler implementation ********************/

