/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastproductiondefinition.h"

struct _GroAstProductionDefinitionPrivate {
	GroRunIToken *lhsName;
	GroRunIToken *ruleList;
};


G_DEFINE_TYPE_WITH_CODE(GroAstProductionDefinition, groast_production_definition, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstProductionDefinition)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_production_definition_class_init(GroAstProductionDefinitionClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_production_definition_init(GroAstProductionDefinition *instance) {
}

static void l_dispose(GObject *object) {
	GroAstProductionDefinition *instance = GROAST_PRODUCTION_DEFINITION(object);
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->lhsName);
	L_SAFE_UNREF_PTR(priv->ruleList);
	G_OBJECT_CLASS(groast_production_definition_parent_class)->dispose(object);
}

GroAstProductionDefinition *groast_production_definition_new_1(GroRunIToken *lhsName, GroRunIToken *ruleList) {
	GroAstProductionDefinition *instance = g_object_new(GROAST_TYPE_PRODUCTION_DEFINITION, NULL);
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(instance);
	priv->lhsName = L_SAFE_REF_PTR(lhsName);
	priv->ruleList = L_SAFE_REF_PTR(ruleList);
	return instance;
}

GroRunIToken *groast_production_definition_tk_lhsName(GroAstProductionDefinition *self) {
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(self);
	return priv->lhsName;
}

CatStringWo *groast_production_definition_get_lhsName(GroAstProductionDefinition *self) {
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->lhsName);
}

GroRunIToken *groast_production_definition_tk_ruleList(GroAstProductionDefinition *self) {
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(self);
	return priv->ruleList;
}

GroAstRhsRuleList *groast_production_definition_get_ruleList(GroAstProductionDefinition *self) {
	GroAstProductionDefinitionPrivate *priv = groast_production_definition_get_instance_private(self);
	return (GroAstRhsRuleList *) grorun_itoken_get_value(priv->ruleList);
}

