/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groastproductiondefinitionlist.h"

struct _GroAstProductionDefinitionListPrivate {
	GroRunIToken *plist;
	GroRunIToken *prod;
};


G_DEFINE_TYPE_WITH_CODE(GroAstProductionDefinitionList, groast_production_definition_list, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstProductionDefinitionList)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_production_definition_list_class_init(GroAstProductionDefinitionListClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_production_definition_list_init(GroAstProductionDefinitionList *instance) {
}

static void l_dispose(GObject *object) {
	GroAstProductionDefinitionList *instance = GROAST_PRODUCTION_DEFINITION_LIST(object);
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->plist);
	L_SAFE_UNREF_PTR(priv->prod);
	G_OBJECT_CLASS(groast_production_definition_list_parent_class)->dispose(object);
}

CatArrayWo *groast_production_definition_list_enlist(GroAstProductionDefinitionList *self) {
 
	CatArrayWo *result = cat_array_wo_new();
	GroAstProductionDefinitionList *tdl = self;
	while(tdl) {
		GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(tdl);
		cat_array_wo_append(result, (GObject *) priv->prod);
		if (priv->plist==NULL) {
			break;
		}
		tdl = (GroAstProductionDefinitionList *) grorun_itoken_get_value(priv->plist);
	}
	cat_array_wo_reverse(result);
	return result;
  
}

GroAstProductionDefinitionList *groast_production_definition_list_new_1(GroRunIToken *plist, GroRunIToken *prod) {
	GroAstProductionDefinitionList *instance = g_object_new(GROAST_TYPE_PRODUCTION_DEFINITION_LIST, NULL);
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(instance);
	priv->plist = L_SAFE_REF_PTR(plist);
	priv->prod = L_SAFE_REF_PTR(prod);
	return instance;
}

GroAstProductionDefinitionList *groast_production_definition_list_new_2(GroRunIToken *prod) {
	GroAstProductionDefinitionList *instance = g_object_new(GROAST_TYPE_PRODUCTION_DEFINITION_LIST, NULL);
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(instance);
	priv->plist = NULL;
	priv->prod = L_SAFE_REF_PTR(prod);
	return instance;
}

GroRunIToken *groast_production_definition_list_tk_plist(GroAstProductionDefinitionList *self) {
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(self);
	return priv->plist;
}

GroAstProductionDefinitionList *groast_production_definition_list_get_plist(GroAstProductionDefinitionList *self) {
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(self);
	return (GroAstProductionDefinitionList *) grorun_itoken_get_value(priv->plist);
}

GroRunIToken *groast_production_definition_list_tk_prod(GroAstProductionDefinitionList *self) {
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(self);
	return priv->prod;
}

GroAstProductionDefinition *groast_production_definition_list_get_prod(GroAstProductionDefinitionList *self) {
	GroAstProductionDefinitionListPrivate *priv = groast_production_definition_list_get_instance_private(self);
	return (GroAstProductionDefinition *) grorun_itoken_get_value(priv->prod);
}

