/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTSYMBOL_PART_H_
#define GROASTSYMBOL_PART_H_

#include <caterpillar.h>
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_SYMBOL_PART              (groast_symbol_part_get_type())
#define GROAST_SYMBOL_PART(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_symbol_part_get_type(), GroAstSymbolPart))
#define GROAST_SYMBOL_PART_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_SYMBOL_PART, GroAstSymbolPartClass))
#define GROAST_IS_SYMBOL_PART(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_SYMBOL_PART))
#define GROAST_IS_SYMBOL_PART_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_SYMBOL_PART))
#define GROAST_SYMBOL_PART_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_SYMBOL_PART, GroAstSymbolPartClass))


typedef struct _GroAstSymbolPart               GroAstSymbolPart;
typedef struct _GroAstSymbolPartPrivate        GroAstSymbolPartPrivate;
typedef struct _GroAstSymbolPartClass          GroAstSymbolPartClass;


struct _GroAstSymbolPart {
	GObject parent;
};

struct _GroAstSymbolPartClass {
	GObjectClass parent_class;
};


GType groast_symbol_part_get_type();

GroAstSymbolPart *groast_symbol_part_new_1(GroRunIToken *symName, GroRunIToken *label);
GroRunIToken *groast_symbol_part_tk_symName(GroAstSymbolPart *self);
CatStringWo *groast_symbol_part_get_symName(GroAstSymbolPart *self);
GroRunIToken *groast_symbol_part_tk_label(GroAstSymbolPart *self);
CatStringWo *groast_symbol_part_get_label(GroAstSymbolPart *self);

G_END_DECLS

#endif /* GROASTSYMBOL_PART_H_ */
