/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTRHS_RULE_LIST_H_
#define GROASTRHS_RULE_LIST_H_

#include "groastrhsrule.h"
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_RHS_RULE_LIST              (groast_rhs_rule_list_get_type())
#define GROAST_RHS_RULE_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_rhs_rule_list_get_type(), GroAstRhsRuleList))
#define GROAST_RHS_RULE_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_RHS_RULE_LIST, GroAstRhsRuleListClass))
#define GROAST_IS_RHS_RULE_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_RHS_RULE_LIST))
#define GROAST_IS_RHS_RULE_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_RHS_RULE_LIST))
#define GROAST_RHS_RULE_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_RHS_RULE_LIST, GroAstRhsRuleListClass))


typedef struct _GroAstRhsRuleList               GroAstRhsRuleList;
typedef struct _GroAstRhsRuleListPrivate        GroAstRhsRuleListPrivate;
typedef struct _GroAstRhsRuleListClass          GroAstRhsRuleListClass;


struct _GroAstRhsRuleList {
	GObject parent;
};

struct _GroAstRhsRuleListClass {
	GObjectClass parent_class;
};


GType groast_rhs_rule_list_get_type();

CatArrayWo *groast_rhs_rule_list_enlist(GroAstRhsRuleList *self);
GroAstRhsRuleList *groast_rhs_rule_list_new_1(GroRunIToken *ruleList, GroRunIToken *rule);
GroAstRhsRuleList *groast_rhs_rule_list_new_2(GroRunIToken *rule);
GroRunIToken *groast_rhs_rule_list_tk_ruleList(GroAstRhsRuleList *self);
GroAstRhsRuleList *groast_rhs_rule_list_get_ruleList(GroAstRhsRuleList *self);
GroRunIToken *groast_rhs_rule_list_tk_rule(GroAstRhsRuleList *self);
GroAstRhsRule *groast_rhs_rule_list_get_rule(GroAstRhsRuleList *self);

G_END_DECLS

#endif /* GROASTRHS_RULE_LIST_H_ */
