/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTCODE_DEFINITION_H_
#define GROASTCODE_DEFINITION_H_

#include <caterpillar.h>
#include "groastprodruleref.h"
#include "grorunfork.h"

G_BEGIN_DECLS

#define GROAST_TYPE_CODE_DEFINITION              (groast_code_definition_get_type())
#define GROAST_CODE_DEFINITION(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_code_definition_get_type(), GroAstCodeDefinition))
#define GROAST_CODE_DEFINITION_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_CODE_DEFINITION, GroAstCodeDefinitionClass))
#define GROAST_IS_CODE_DEFINITION(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_CODE_DEFINITION))
#define GROAST_IS_CODE_DEFINITION_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_CODE_DEFINITION))
#define GROAST_CODE_DEFINITION_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_CODE_DEFINITION, GroAstCodeDefinitionClass))


typedef struct _GroAstCodeDefinition               GroAstCodeDefinition;
typedef struct _GroAstCodeDefinitionPrivate        GroAstCodeDefinitionPrivate;
typedef struct _GroAstCodeDefinitionClass          GroAstCodeDefinitionClass;


struct _GroAstCodeDefinition {
	GObject parent;
};

struct _GroAstCodeDefinitionClass {
	GObjectClass parent_class;
};


GType groast_code_definition_get_type();

GroAstCodeDefinition *groast_code_definition_new_1(GroRunIToken *ruleRef, GroRunIToken *codeText);
GroRunIToken *groast_code_definition_tk_ruleRef(GroAstCodeDefinition *self);
GroAstProdRuleRef *groast_code_definition_get_ruleRef(GroAstCodeDefinition *self);
GroRunIToken *groast_code_definition_tk_codeText(GroAstCodeDefinition *self);
CatStringWo *groast_code_definition_get_codeText(GroAstCodeDefinition *self);

G_END_DECLS

#endif /* GROASTCODE_DEFINITION_H_ */
