/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTTERMINAL_DECLARATION_H_
#define GROASTTERMINAL_DECLARATION_H_

#include "grorunfork.h"
#include "groastidlist.h"

G_BEGIN_DECLS

#define GROAST_TYPE_TERMINAL_DECLARATION              (groast_terminal_declaration_get_type())
#define GROAST_TERMINAL_DECLARATION(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_terminal_declaration_get_type(), GroAstTerminalDeclaration))
#define GROAST_TERMINAL_DECLARATION_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_TERMINAL_DECLARATION, GroAstTerminalDeclarationClass))
#define GROAST_IS_TERMINAL_DECLARATION(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_TERMINAL_DECLARATION))
#define GROAST_IS_TERMINAL_DECLARATION_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_TERMINAL_DECLARATION))
#define GROAST_TERMINAL_DECLARATION_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_TERMINAL_DECLARATION, GroAstTerminalDeclarationClass))


typedef struct _GroAstTerminalDeclaration               GroAstTerminalDeclaration;
typedef struct _GroAstTerminalDeclarationPrivate        GroAstTerminalDeclarationPrivate;
typedef struct _GroAstTerminalDeclarationClass          GroAstTerminalDeclarationClass;


struct _GroAstTerminalDeclaration {
	GObject parent;
};

struct _GroAstTerminalDeclarationClass {
	GObjectClass parent_class;
};


GType groast_terminal_declaration_get_type();

CatArrayWo *groast_terminal_declaration_enlist(GroAstTerminalDeclaration *self);
GroAstTerminalDeclaration *groast_terminal_declaration_new_1(GroRunIToken *ids);
GroAstTerminalDeclaration *groast_terminal_declaration_new_2();
GroRunIToken *groast_terminal_declaration_tk_ids(GroAstTerminalDeclaration *self);
GroAstIdList *groast_terminal_declaration_get_ids(GroAstTerminalDeclaration *self);

G_END_DECLS

#endif /* GROASTTERMINAL_DECLARATION_H_ */
