/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#ifndef GROASTRHS_SUB_LIST_H_
#define GROASTRHS_SUB_LIST_H_

#include "grorunfork.h"
#include "../../src/ast/groastirhspart.h"

G_BEGIN_DECLS

#define GROAST_TYPE_RHS_SUB_LIST              (groast_rhs_sub_list_get_type())
#define GROAST_RHS_SUB_LIST(obj)              (G_TYPE_CHECK_INSTANCE_CAST ((obj), groast_rhs_sub_list_get_type(), GroAstRhsSubList))
#define GROAST_RHS_SUB_LIST_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), GROAST_TYPE_RHS_SUB_LIST, GroAstRhsSubListClass))
#define GROAST_IS_RHS_SUB_LIST(obj)           (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GROAST_TYPE_RHS_SUB_LIST))
#define GROAST_IS_RHS_SUB_LIST_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), GROAST_TYPE_RHS_SUB_LIST))
#define GROAST_RHS_SUB_LIST_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), GROAST_TYPE_RHS_SUB_LIST, GroAstRhsSubListClass))


typedef struct _GroAstRhsSubList               GroAstRhsSubList;
typedef struct _GroAstRhsSubListPrivate        GroAstRhsSubListPrivate;
typedef struct _GroAstRhsSubListClass          GroAstRhsSubListClass;


struct _GroAstRhsSubList {
	GObject parent;
};

struct _GroAstRhsSubListClass {
	GObjectClass parent_class;
};


GType groast_rhs_sub_list_get_type();

CatArrayWo *groast_rhs_sub_list_enlist(GroAstRhsSubList *self);
GroAstRhsSubList *groast_rhs_sub_list_new_1(GroRunIToken *subList, GroRunIToken *sub);
GroAstRhsSubList *groast_rhs_sub_list_new_2(GroRunIToken *sub);
GroRunIToken *groast_rhs_sub_list_tk_sub(GroAstRhsSubList *self);
GroAstIRhsPart *groast_rhs_sub_list_get_sub(GroAstRhsSubList *self);
GroRunIToken *groast_rhs_sub_list_tk_subList(GroAstRhsSubList *self);
GroAstIRhsPart *groast_rhs_sub_list_get_subList(GroAstRhsSubList *self);

G_END_DECLS

#endif /* GROASTRHS_SUB_LIST_H_ */
