/* This file was generated by Gross-CC on 2016.11.30 AD at 21:31:20 CET */
#include "groasttypedefinition.h"

struct _GroAstTypeDefinitionPrivate {
	GroRunIToken *symids;
	GroRunIToken *symtype;
};


G_DEFINE_TYPE_WITH_CODE(GroAstTypeDefinition, groast_type_definition, G_TYPE_OBJECT,
		G_ADD_PRIVATE(GroAstTypeDefinition)
);

#define L_SAFE_UNREF_PTR(p) { void *ptr = p; p = NULL; if (ptr) { g_object_unref(ptr); } }
static G_GNUC_UNUSED void *L_SAFE_REF_PTR(void *p) { if (p) { g_object_ref(p); } return p; }

static void l_dispose(GObject *object);

static void groast_type_definition_class_init(GroAstTypeDefinitionClass *clazz) {
	GObjectClass *object_class = G_OBJECT_CLASS(clazz);
	object_class->dispose = l_dispose;
}

static void groast_type_definition_init(GroAstTypeDefinition *instance) {
}

static void l_dispose(GObject *object) {
	GroAstTypeDefinition *instance = GROAST_TYPE_DEFINITION(object);
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(instance);
	L_SAFE_UNREF_PTR(priv->symids);
	L_SAFE_UNREF_PTR(priv->symtype);
	G_OBJECT_CLASS(groast_type_definition_parent_class)->dispose(object);
}

GroAstTypeDefinition *groast_type_definition_new_1(GroRunIToken *symtype, GroRunIToken *symids) {
	GroAstTypeDefinition *instance = g_object_new(GROAST_TYPE_TYPE_DEFINITION, NULL);
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(instance);
	priv->symids = L_SAFE_REF_PTR(symids);
	priv->symtype = L_SAFE_REF_PTR(symtype);
	return instance;
}

GroRunIToken *groast_type_definition_tk_symids(GroAstTypeDefinition *self) {
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(self);
	return priv->symids;
}

GroAstIdList *groast_type_definition_get_symids(GroAstTypeDefinition *self) {
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(self);
	return (GroAstIdList *) grorun_itoken_get_value(priv->symids);
}

GroRunIToken *groast_type_definition_tk_symtype(GroAstTypeDefinition *self) {
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(self);
	return priv->symtype;
}

CatStringWo *groast_type_definition_get_symtype(GroAstTypeDefinition *self) {
	GroAstTypeDefinitionPrivate *priv = groast_type_definition_get_instance_private(self);
	return (CatStringWo *) grorun_itoken_get_value(priv->symtype);
}

